import { RankdlePuzzleDefinition } from './rankdle.models';

export const RANKDLE_PUZZLES: readonly RankdlePuzzleDefinition[] = [
  {
    id: 'planetas-diametro',
    category: 'Astronomía',
    icon: 'fa-solid fa-earth-americas',
    question: 'Ordená estos planetas por su diámetro ecuatorial.',
    lowerLabel: 'Más pequeño',
    upperLabel: 'Más grande',
    sourceLabel: 'NASA · Planetary Fact Sheet',
    sourceUrl: 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/',
    items: [
      { id: 'mercurio', name: 'Mercurio', value: 4879, displayValue: '4.879 km', note: 'Es el planeta más cercano al Sol.' },
      { id: 'marte', name: 'Marte', value: 6792, displayValue: '6.792 km', note: 'Su diámetro es aproximadamente la mitad del terrestre.' },
      { id: 'venus', name: 'Venus', value: 12104, displayValue: '12.104 km', note: 'Tiene un tamaño muy parecido al de la Tierra.' },
      { id: 'tierra', name: 'Tierra', value: 12756, displayValue: '12.756 km', note: 'Es el mayor de los planetas rocosos.' },
      { id: 'neptuno', name: 'Neptuno', value: 49528, displayValue: '49.528 km', note: 'Es un gigante de hielo.' },
    ],
  },
  {
    id: 'montanas-altura',
    category: 'Geografía',
    icon: 'fa-solid fa-mountain-sun',
    question: 'Ordená estas montañas por su altura sobre el nivel del mar.',
    lowerLabel: 'Más baja',
    upperLabel: 'Más alta',
    sourceLabel: 'Encyclopaedia Britannica',
    sourceUrl: 'https://www.britannica.com/topic/list-of-mountains-2039407',
    items: [
      { id: 'fuji', name: 'Monte Fuji', value: 3776, displayValue: '3.776 m', note: 'Es la cumbre más alta de Japón.' },
      { id: 'mont-blanc', name: 'Mont Blanc', value: 4806, displayValue: '4.806 m', note: 'Se alza en los Alpes, entre Francia e Italia.' },
      { id: 'kilimanjaro', name: 'Kilimanjaro', value: 5895, displayValue: '5.895 m', note: 'Es la montaña más alta de África.' },
      { id: 'aconcagua', name: 'Aconcagua', value: 6961, displayValue: '6.961 m', note: 'Es la cumbre más alta de América.' },
      { id: 'everest', name: 'Monte Everest', value: 8849, displayValue: '8.849 m', note: 'Es el punto más alto sobre el nivel del mar.' },
    ],
  },
  {
    id: 'paises-superficie',
    category: 'Mapamundi',
    icon: 'fa-solid fa-map',
    question: 'Ordená estos países sudamericanos por superficie.',
    lowerLabel: 'Menor superficie',
    upperLabel: 'Mayor superficie',
    sourceLabel: 'Banco Mundial · Surface area',
    sourceUrl: 'https://data.worldbank.org/indicator/AG.SRF.TOTL.K2',
    items: [
      { id: 'ecuador', name: 'Ecuador', value: 256370, displayValue: '256.370 km²', note: 'Está atravesado por la línea ecuatorial.' },
      { id: 'paraguay', name: 'Paraguay', value: 406752, displayValue: '406.752 km²', note: 'Es uno de los dos países sin litoral marítimo de Sudamérica.' },
      { id: 'chile', name: 'Chile', value: 756102, displayValue: '756.102 km²', note: 'Se extiende a lo largo del borde occidental del continente.' },
      { id: 'peru', name: 'Perú', value: 1285216, displayValue: '1.285.216 km²', note: 'Combina costa del Pacífico, Andes y Amazonia.' },
      { id: 'argentina', name: 'Argentina', value: 2780400, displayValue: '2.780.400 km²', note: 'Es el segundo país más extenso de Sudamérica.' },
    ],
  },
  {
    id: 'elementos-atomicos',
    category: 'Química',
    icon: 'fa-solid fa-flask',
    question: 'Ordená estos elementos por su número atómico.',
    lowerLabel: 'Número menor',
    upperLabel: 'Número mayor',
    sourceLabel: 'IUPAC · Periodic Table',
    sourceUrl: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
    items: [
      { id: 'carbono', name: 'Carbono', value: 6, displayValue: '6', note: 'Es la base química de la vida conocida.' },
      { id: 'oxigeno', name: 'Oxígeno', value: 8, displayValue: '8', note: 'Representa cerca del 21 % de la atmósfera terrestre.' },
      { id: 'aluminio', name: 'Aluminio', value: 13, displayValue: '13', note: 'Es un metal liviano y muy abundante.' },
      { id: 'hierro', name: 'Hierro', value: 26, displayValue: '26', note: 'Es el principal componente del núcleo terrestre.' },
      { id: 'oro', name: 'Oro', value: 79, displayValue: '79', note: 'Su símbolo químico es Au.' },
    ],
  },
  {
    id: 'rascacielos-altura',
    category: 'Arquitectura',
    icon: 'fa-solid fa-city',
    question: 'Ordená estos edificios por su altura arquitectónica.',
    lowerLabel: 'Más bajo',
    upperLabel: 'Más alto',
    sourceLabel: 'Council on Tall Buildings and Urban Habitat',
    sourceUrl: 'https://www.skyscrapercenter.com/buildings',
    items: [
      { id: 'empire-state', name: 'Empire State Building', value: 381, displayValue: '381 m', note: 'Fue el edificio más alto del mundo entre 1931 y 1970.' },
      { id: 'petronas', name: 'Torres Petronas', value: 452, displayValue: '452 m', note: 'Las torres gemelas se encuentran en Kuala Lumpur.' },
      { id: 'taipei-101', name: 'Taipei 101', value: 508, displayValue: '508 m', note: 'Su diseño está inspirado en una pagoda.' },
      { id: 'shanghai-tower', name: 'Torre de Shanghái', value: 632, displayValue: '632 m', note: 'Su fachada gira suavemente a medida que asciende.' },
      { id: 'burj-khalifa', name: 'Burj Khalifa', value: 828, displayValue: '828 m', note: 'Es el edificio más alto del mundo.' },
    ],
  },
  {
    id: 'videojuegos-lanzamiento',
    category: 'Videojuegos',
    icon: 'fa-solid fa-gamepad',
    question: 'Ordená estos videojuegos por su primer lanzamiento.',
    lowerLabel: 'Más antiguo',
    upperLabel: 'Más reciente',
    sourceLabel: 'The Strong · World Video Game Hall of Fame',
    sourceUrl: 'https://www.worldvideogamehalloffame.org/games/',
    items: [
      { id: 'tetris', name: 'Tetris', value: 1984, displayValue: '1984', note: 'Alexey Pajitnov lo creó en la Unión Soviética.' },
      { id: 'super-mario-bros', name: 'Super Mario Bros.', value: 1985, displayValue: '1985', note: 'Se publicó originalmente para Famicom en Japón.' },
      { id: 'sonic', name: 'Sonic the Hedgehog', value: 1991, displayValue: '1991', note: 'Debutó en la consola Sega Genesis/Mega Drive.' },
      { id: 'minecraft', name: 'Minecraft', value: 2011, displayValue: '2011', note: 'Su lanzamiento completo llegó después de una etapa pública de desarrollo.' },
      { id: 'fortnite', name: 'Fortnite', value: 2017, displayValue: '2017', note: 'Epic Games lanzó primero su modo Save the World.' },
    ],
  },
  {
    id: 'animales-peso',
    category: 'Naturaleza',
    icon: 'fa-solid fa-paw',
    question: 'Ordená estos animales por su peso adulto aproximado.',
    lowerLabel: 'Más liviano',
    upperLabel: 'Más pesado',
    sourceLabel: 'Smithsonian’s National Zoo',
    sourceUrl: 'https://nationalzoo.si.edu/animals',
    items: [
      { id: 'suricata', name: 'Suricata', value: 1, displayValue: '≈ 1 kg', note: 'Vive en grupos y se turna para vigilar.' },
      { id: 'carpincho', name: 'Carpincho', value: 55, displayValue: '≈ 55 kg', note: 'Es el roedor viviente de mayor tamaño.' },
      { id: 'leon', name: 'León', value: 190, displayValue: '≈ 190 kg', note: 'Los machos adultos suelen ser más pesados que las hembras.' },
      { id: 'oso-polar', name: 'Oso polar', value: 450, displayValue: '≈ 450 kg', note: 'Es el carnívoro terrestre de mayor tamaño.' },
      { id: 'elefante-africano', name: 'Elefante africano', value: 6000, displayValue: '≈ 6.000 kg', note: 'Es el animal terrestre más pesado.' },
    ],
  },
  {
    id: 'peliculas-duracion',
    category: 'Cine',
    icon: 'fa-solid fa-film',
    question: 'Ordená estas películas por su duración.',
    lowerLabel: 'Más corta',
    upperLabel: 'Más larga',
    sourceLabel: 'British Film Institute',
    sourceUrl: 'https://www.bfi.org.uk/',
    items: [
      { id: 'toy-story', name: 'Toy Story', value: 81, displayValue: '81 min', note: 'Fue el primer largometraje animado íntegramente por computadora.' },
      { id: 'rey-leon', name: 'El rey león', value: 88, displayValue: '88 min', note: 'La película animada original se estrenó en 1994.' },
      { id: 'matrix', name: 'Matrix', value: 136, displayValue: '136 min', note: 'Las Wachowski combinaron ciencia ficción, acción y filosofía.' },
      { id: 'titanic', name: 'Titanic', value: 194, displayValue: '194 min', note: 'James Cameron dirigió la película estrenada en 1997.' },
      { id: 'padrino-ii', name: 'El padrino II', value: 202, displayValue: '202 min', note: 'Alterna la historia de Michael Corleone con la juventud de Vito.' },
    ],
  },
] as const;
