import { RoscoCategory, RoscoQuestion } from './roscodle.models';

export const ROSCO_ALPHABET = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'Ñ',
  'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
];

export const ROSCO_QUESTIONS: Record<RoscoCategory, RoscoQuestion[]> = {
  players: [
    { letter: 'A', relation: 'starts', clue: 'Delantero argentino, ídolo del Manchester City y autor de un gol agónico que valió una Premier.', answer: 'Agüero', aliases: ['Aguero', 'Kun Aguero', 'Sergio Aguero'] },
    { letter: 'B', relation: 'starts', clue: 'Mediocampista inglés que llegó al Real Madrid desde el Borussia Dortmund.', answer: 'Bellingham', aliases: ['Jude Bellingham'] },
    { letter: 'C', relation: 'starts', clue: 'Portugués, máximo goleador histórico de selecciones masculinas y ganador de cinco Balones de Oro.', answer: 'Cristiano Ronaldo', aliases: ['Cristiano', 'Ronaldo', 'CR7'] },
    { letter: 'D', relation: 'starts', clue: 'Atacante cordobés apodado La Joya, campeón del mundo con Argentina en 2022.', answer: 'Dybala', aliases: ['Paulo Dybala'] },
    { letter: 'E', relation: 'starts', clue: 'Mediocampista argentino campeón del mundo, surgido en River y transferido a Chelsea.', answer: 'Enzo Fernández', aliases: ['Enzo Fernandez', 'Enzo'] },
    { letter: 'F', relation: 'starts', clue: 'Talentoso zurdo inglés formado en la cantera del Manchester City.', answer: 'Foden', aliases: ['Phil Foden'] },
    { letter: 'G', relation: 'starts', clue: 'Atacante francés que festeja algunos goles imitando una llamada telefónica.', answer: 'Griezmann', aliases: ['Antoine Griezmann'] },
    { letter: 'H', relation: 'starts', clue: 'Goleador noruego del Manchester City, conocido por su potencia y sus récords precoces.', answer: 'Haaland', aliases: ['Erling Haaland'] },
    { letter: 'I', relation: 'starts', clue: 'Autor del gol que le dio a España el Mundial de 2010.', answer: 'Iniesta', aliases: ['Andres Iniesta', 'Andrés Iniesta'] },
    { letter: 'J', relation: 'starts', clue: 'Delantero argentino apodado La Araña, campeón del mundo en Qatar.', answer: 'Julián Álvarez', aliases: ['Julian Alvarez', 'Julián Alvarez'] },
    { letter: 'K', relation: 'starts', clue: 'Mediapunta brasileño que ganó el Balón de Oro en 2007 jugando para el Milan.', answer: 'Kaká', aliases: ['Kaka', 'Ricardo Kaka'] },
    { letter: 'L', relation: 'starts', clue: 'Delantero polaco, figura histórica del Bayern y goleador del Barcelona.', answer: 'Lewandowski', aliases: ['Robert Lewandowski'] },
    { letter: 'M', relation: 'starts', clue: 'Capitán argentino campeón del mundo en 2022 y ganador de ocho Balones de Oro.', answer: 'Messi', aliases: ['Lionel Messi', 'Leo Messi'] },
    { letter: 'N', relation: 'starts', clue: 'Brasileño surgido en Santos que formó la MSN junto a Messi y Suárez.', answer: 'Neymar', aliases: ['Neymar Jr', 'Neymar Junior'] },
    { letter: 'Ñ', relation: 'contains', clue: 'Delantero del Athletic Club, internacional con Ghana y hermano mayor de Nico.', answer: 'Iñaki Williams', aliases: ['Inaki Williams', 'Iñaki'] },
    { letter: 'O', relation: 'starts', clue: 'Extremo argentino surgido en River, con pasos por Sevilla y la selección.', answer: 'Ocampos', aliases: ['Lucas Ocampos'] },
    { letter: 'P', relation: 'starts', clue: 'Mediocampista canario del Barcelona, ganador del Golden Boy en 2021.', answer: 'Pedri', aliases: ['Pedro Gonzalez', 'Pedro González'] },
    { letter: 'Q', relation: 'contains', clue: 'Enganche argentino, máximo ídolo de Boca y especialista en tiros libres.', answer: 'Riquelme', aliases: ['Juan Roman Riquelme', 'Juan Román Riquelme'] },
    { letter: 'R', relation: 'starts', clue: 'Brasileño de sonrisa inconfundible, campeón del mundo en 2002 y Balón de Oro en 2005.', answer: 'Ronaldinho', aliases: ['Ronaldinho Gaucho', 'Ronaldinho Gaúcho'] },
    { letter: 'S', relation: 'starts', clue: 'Delantero egipcio, figura del Liverpool y apodado el Faraón.', answer: 'Salah', aliases: ['Mohamed Salah', 'Mo Salah'] },
    { letter: 'T', relation: 'starts', clue: 'Lateral argentino campeón del mundo, nacido en Rafael Calzada.', answer: 'Tagliafico', aliases: ['Nicolas Tagliafico', 'Nicolás Tagliafico'] },
    { letter: 'U', relation: 'starts', clue: 'Mediocampista uruguayo de marca, internacional con la Celeste.', answer: 'Ugarte', aliases: ['Manuel Ugarte'] },
    { letter: 'V', relation: 'starts', clue: 'Extremo brasileño del Real Madrid, autor del gol en la final de Champions 2022.', answer: 'Vinícius', aliases: ['Vinicius', 'Vinicius Junior', 'Vini Jr'] },
    { letter: 'W', relation: 'starts', clue: 'Delantero neerlandés que marcó dos goles ante Argentina en los cuartos de Qatar 2022.', answer: 'Weghorst', aliases: ['Wout Weghorst'] },
    { letter: 'X', relation: 'starts', clue: 'Legendario mediocampista del Barcelona y de la selección española.', answer: 'Xavi', aliases: ['Xavi Hernandez', 'Xavi Hernández'] },
    { letter: 'Y', relation: 'contains', clue: 'Joven extremo español del Barcelona que brilló en la Eurocopa 2024.', answer: 'Lamine Yamal', aliases: ['Yamal'] },
    { letter: 'Z', relation: 'starts', clue: 'Francés de origen argelino, campeón del mundo en 1998 y héroe de la Novena del Real Madrid.', answer: 'Zidane', aliases: ['Zinedine Zidane'] },
  ],
  teams: [
    { letter: 'A', relation: 'starts', clue: 'Club del norte de Londres conocido como los Gunners.', answer: 'Arsenal' },
    { letter: 'B', relation: 'starts', clue: 'Club catalán que juega de local en el Camp Nou.', answer: 'Barcelona', aliases: ['FC Barcelona', 'Barca', 'Barça'] },
    { letter: 'C', relation: 'starts', clue: 'Club londinense vestido de azul que juega en Stamford Bridge.', answer: 'Chelsea' },
    { letter: 'D', relation: 'starts', clue: 'Club alemán cuyo estadio alberga el famoso Muro Amarillo.', answer: 'Dortmund', aliases: ['Borussia Dortmund', 'BVB'] },
    { letter: 'E', relation: 'starts', clue: 'Club de La Plata apodado el Pincha, cuatro veces campeón de América.', answer: 'Estudiantes', aliases: ['Estudiantes de La Plata'] },
    { letter: 'F', relation: 'starts', clue: 'Club italiano de camiseta violeta y sede en Florencia.', answer: 'Fiorentina' },
    { letter: 'G', relation: 'starts', clue: 'Gigante turco de Estambul cuyos colores son rojo y amarillo.', answer: 'Galatasaray' },
    { letter: 'H', relation: 'starts', clue: 'Club argentino de Parque Patricios, apodado el Globo.', answer: 'Huracán', aliases: ['Huracan'] },
    { letter: 'I', relation: 'starts', clue: 'Club de Milán vestido de negro y azul, conocido como los Nerazzurri.', answer: 'Inter', aliases: ['Inter de Milan', 'Inter de Milán', 'Internazionale'] },
    { letter: 'J', relation: 'starts', clue: 'Club de Turín apodado la Vecchia Signora.', answer: 'Juventus', aliases: ['Juve'] },
    { letter: 'K', relation: 'starts', clue: 'Histórico club alemán cuyo nombre completo incluye la ciudad de Lautern.', answer: 'Kaiserslautern', aliases: ['FC Kaiserslautern'] },
    { letter: 'L', relation: 'starts', clue: 'Club inglés de Anfield que canta You’ll Never Walk Alone.', answer: 'Liverpool' },
    { letter: 'M', relation: 'starts', clue: 'Club italiano rossonero, siete veces campeón de Europa.', answer: 'Milan', aliases: ['AC Milan'] },
    { letter: 'N', relation: 'starts', clue: 'Club del sur de Italia asociado para siempre con Diego Maradona.', answer: 'Napoli', aliases: ['Napoles', 'Nápoles'] },
    { letter: 'Ñ', relation: 'contains', clue: 'Club uruguayo aurinegro, clásico rival de Nacional.', answer: 'Peñarol', aliases: ['Penarol'] },
    { letter: 'O', relation: 'starts', clue: 'Club francés del Velódrome que ganó la Champions en 1993.', answer: 'Olympique de Marsella', aliases: ['Olympique de Marseille', 'Marsella', 'Marseille'] },
    { letter: 'P', relation: 'starts', clue: 'Club portugués de camiseta azul y blanca que juega en el estadio do Dragão.', answer: 'Porto', aliases: ['Oporto', 'FC Porto'] },
    { letter: 'Q', relation: 'starts', clue: 'Club de Azerbaiyán habitual participante de competiciones europeas.', answer: 'Qarabağ', aliases: ['Qarabag'] },
    { letter: 'R', relation: 'starts', clue: 'Club argentino del Monumental, apodado el Millonario.', answer: 'River Plate', aliases: ['River'] },
    { letter: 'S', relation: 'starts', clue: 'Club andaluz récord de títulos de Europa League.', answer: 'Sevilla', aliases: ['Sevilla FC'] },
    { letter: 'T', relation: 'starts', clue: 'Club del norte de Londres apodado los Spurs.', answer: 'Tottenham', aliases: ['Tottenham Hotspur', 'Spurs'] },
    { letter: 'U', relation: 'starts', clue: 'Club italiano de Friuli que viste de blanco y negro.', answer: 'Udinese' },
    { letter: 'V', relation: 'starts', clue: 'Club español de Mestalla cuyo escudo lleva un murciélago.', answer: 'Valencia', aliases: ['Valencia CF'] },
    { letter: 'W', relation: 'starts', clue: 'Club alemán patrocinado históricamente por Volkswagen.', answer: 'Wolfsburg', aliases: ['VfL Wolfsburg'] },
    { letter: 'X', relation: 'starts', clue: 'Club andaluz de Jerez de la Frontera, escrito con X.', answer: 'Xerez', aliases: ['Xerez CD'] },
    { letter: 'Y', relation: 'starts', clue: 'Club suizo de Berna cuyo nombre en inglés significa “chicos jóvenes”.', answer: 'Young Boys', aliases: ['BSC Young Boys'] },
    { letter: 'Z', relation: 'starts', clue: 'Club ruso de San Petersburgo vestido tradicionalmente de azul.', answer: 'Zenit', aliases: ['Zenit de San Petersburgo'] },
  ],
  boca: [
    { letter: 'A', relation: 'starts', clue: 'Ídolo de los años sesenta conocido como Rojitas.', answer: 'Ángel Clemente Rojas', aliases: ['Angel Clemente Rojas', 'Rojitas'] },
    { letter: 'B', relation: 'starts', clue: 'Mediocampista surgido en el club, uno de los futbolistas más ganadores de su historia.', answer: 'Battaglia', aliases: ['Sebastian Battaglia', 'Sebastián Battaglia'] },
    { letter: 'C', relation: 'starts', clue: 'Mediocampista que convirtió el penal decisivo en la final Intercontinental de 2003.', answer: 'Cascini', aliases: ['Raul Cascini', 'Raúl Cascini'] },
    { letter: 'D', relation: 'starts', clue: 'El Chelo, delantero que marcó en la final de la Libertadores 2003 ante Santos.', answer: 'Delgado', aliases: ['Marcelo Delgado', 'Chelo Delgado'] },
    { letter: 'E', relation: 'starts', clue: 'Nombre formal de la cancha mundialmente conocida como La Bombonera.', answer: 'Estadio Alberto J. Armando', aliases: ['Estadio Alberto J Armando', 'Alberto J Armando'] },
    { letter: 'F', relation: 'starts', clue: 'Lateral colombiano que llegó al club en 2016.', answer: 'Fabra', aliases: ['Frank Fabra'] },
    { letter: 'G', relation: 'starts', clue: 'Delantero apodado el Mellizo, figura de múltiples títulos con Carlos Bianchi.', answer: 'Guillermo Barros Schelotto', aliases: ['Guillermo', 'Barros Schelotto', 'Mellizo'] },
    { letter: 'H', relation: 'starts', clue: 'Delantero venezolano que vistió la azul y oro entre 2019 y 2021.', answer: 'Hurtado', aliases: ['Jan Hurtado'] },
    { letter: 'I', relation: 'starts', clue: 'Lateral derecho formoseño apodado el Negro, campeón del mundo con Boca en 2000.', answer: 'Ibarra', aliases: ['Hugo Ibarra', 'Negro Ibarra'] },
    { letter: 'J', relation: 'starts', clue: 'Nombre de pila del máximo ídolo y dueño histórico de la camiseta número 10.', answer: 'Juan Román Riquelme', aliases: ['Juan Roman Riquelme', 'Riquelme', 'Roman'] },
    { letter: 'K', relation: 'contains', clue: 'Delantero japonés que tuvo un breve paso por Boca en 2001.', answer: 'Takahara', aliases: ['Naohiro Takahara'] },
    { letter: 'L', relation: 'starts', clue: 'Apodo del estadio de Boca, famoso por latir cuando tiembla.', answer: 'La Bombonera', aliases: ['Bombonera'] },
    { letter: 'M', relation: 'starts', clue: 'Máximo goleador histórico del club, apodado el Titán.', answer: 'Martín Palermo', aliases: ['Martin Palermo', 'Palermo', 'Titan'] },
    { letter: 'N', relation: 'starts', clue: 'Arquero colombiano-argentino apodado el Mono.', answer: 'Navarro Montoya', aliases: ['Carlos Navarro Montoya', 'Mono Navarro Montoya'] },
    { letter: 'Ñ', relation: 'contains', clue: 'Defensor central surgido en Boca que luego jugó en Europa y en la Selección Argentina.', answer: 'Ezequiel Muñoz', aliases: ['Ezequiel Munoz', 'Muñoz', 'Munoz'] },
    { letter: 'O', relation: 'starts', clue: 'Arquero colombiano campeón Intercontinental en 2000 ante Real Madrid.', answer: 'Óscar Córdoba', aliases: ['Oscar Cordoba', 'Cordoba', 'Córdoba'] },
    { letter: 'P', relation: 'starts', clue: 'Mediocampista surgido en Boca que fue campeón del mundo con Argentina en 2022.', answer: 'Paredes', aliases: ['Leandro Paredes'] },
    { letter: 'Q', relation: 'contains', clue: 'Apellido del enganche que usó la 10 y ganó tres Copas Libertadores con Boca.', answer: 'Riquelme', aliases: ['Juan Roman Riquelme', 'Juan Román Riquelme'] },
    { letter: 'R', relation: 'starts', clue: 'Entrenador que condujo al equipo campeón de la Libertadores 2007.', answer: 'Russo', aliases: ['Miguel Angel Russo', 'Miguel Ángel Russo'] },
    { letter: 'S', relation: 'starts', clue: 'Defensor apodado el Flaco, autor de un gol en la final de la Libertadores 2007.', answer: 'Schiavi', aliases: ['Rolando Schiavi', 'Flaco Schiavi'] },
    { letter: 'T', relation: 'starts', clue: 'El Apache, surgido en el club y campeón de la Libertadores e Intercontinental en 2003.', answer: 'Tevez', aliases: ['Carlos Tevez', 'Carlos Tévez', 'Apache'] },
    { letter: 'U', relation: 'contains', clue: 'Delantero zurdo surgido en Boca, de apellido francés y campeón del Apertura 2011.', answer: 'Mouche', aliases: ['Pablo Mouche'] },
    { letter: 'V', relation: 'starts', clue: 'Mediocampista central surgido en el club y posteriormente transferido al Porto.', answer: 'Varela', aliases: ['Alan Varela'] },
    { letter: 'W', relation: 'starts', clue: 'Defensor surgido en Boca, apodado el Muro, que brilló en la Roma.', answer: 'Walter Samuel', aliases: ['Samuel', 'Walter Adrian Samuel'] },
    { letter: 'X', relation: 'contains', clue: 'Extremo santiagueño apodado el Changuito.', answer: 'Exequiel Zeballos', aliases: ['Zeballos', 'Changuito Zeballos'] },
    { letter: 'Y', relation: 'starts', clue: 'Director técnico que condujo a Boca durante la temporada 1987/88.', answer: 'Yudica', aliases: ['Jose Yudica', 'José Yudica'] },
    { letter: 'Z', relation: 'starts', clue: 'Apellido del Changuito, delantero surgido de las inferiores del club.', answer: 'Zeballos', aliases: ['Exequiel Zeballos', 'Changuito Zeballos'] },
  ],
  river: [
    { letter: 'A', relation: 'starts', clue: 'El Beto, enganche histórico y autor de dos goles en la final del Nacional 1975.', answer: 'Alonso', aliases: ['Norberto Alonso', 'Beto Alonso'] },
    { letter: 'B', relation: 'starts', clue: 'Goleador de los años treinta apodado el Mortero de Rufino.', answer: 'Bernabé Ferreyra', aliases: ['Bernabe Ferreyra', 'Ferreyra'] },
    { letter: 'C', relation: 'starts', clue: 'Delantero apodado el Torito, campeón y goleador en distintas etapas con River.', answer: 'Cavenaghi', aliases: ['Fernando Cavenaghi', 'Torito'] },
    { letter: 'D', relation: 'starts', clue: 'Talentoso zurdo surgido del club, apodado el Cabezón.', answer: "D'Alessandro", aliases: ['Andres D Alessandro', 'Andrés D Alessandro', 'Dalessandro'] },
    { letter: 'E', relation: 'starts', clue: 'El Príncipe uruguayo, ídolo de River y campeón de América y del mundo en 1986.', answer: 'Enzo Francescoli', aliases: ['Francescoli', 'Enzo'] },
    { letter: 'F', relation: 'starts', clue: 'Arquero campeón del mundo en 1978 y uno de los máximos ídolos del arco millonario.', answer: 'Fillol', aliases: ['Ubaldo Fillol', 'Pato Fillol'] },
    { letter: 'G', relation: 'starts', clue: 'El Muñeco, entrenador del ciclo más ganador de la historia moderna del club.', answer: 'Gallardo', aliases: ['Marcelo Gallardo', 'Muñeco Gallardo'] },
    { letter: 'H', relation: 'starts', clue: 'Lateral derecho campeón de América en 1996 y referente de los años noventa.', answer: 'Hernán Díaz', aliases: ['Hernan Diaz', 'Hernán Diaz'] },
    { letter: 'I', relation: 'starts', clue: 'Atacante argentino-paraguayo que jugó en River antes de continuar su carrera en Europa.', answer: 'Iturbe', aliases: ['Juan Manuel Iturbe'] },
    { letter: 'J', relation: 'starts', clue: 'Delantero surgido en River, apodado la Araña y campeón del mundo en Qatar.', answer: 'Julián Álvarez', aliases: ['Julian Alvarez', 'Julián Alvarez', 'Araña'] },
    { letter: 'K', relation: 'starts', clue: 'Mediocampista tucumano surgido en el club y campeón de la Libertadores 2015.', answer: 'Kranevitter', aliases: ['Matias Kranevitter', 'Matías Kranevitter'] },
    { letter: 'L', relation: 'starts', clue: 'Máximo goleador histórico de River y símbolo de La Máquina.', answer: 'Labruna', aliases: ['Angel Labruna', 'Ángel Labruna'] },
    { letter: 'M', relation: 'starts', clue: 'Defensor central campeón de las Libertadores 2015 y 2018.', answer: 'Maidana', aliases: ['Jonatan Maidana'] },
    { letter: 'N', relation: 'starts', clue: 'Apodo del mediocampista Fernández, figura de la Libertadores 2018.', answer: 'Nacho Fernández', aliases: ['Nacho Fernandez', 'Ignacio Fernandez', 'Ignacio Fernández'] },
    { letter: 'Ñ', relation: 'contains', clue: 'Apodo con el que se conoce a Marcelo Gallardo.', answer: 'Muñeco', aliases: ['El Muñeco', 'Muneco'] },
    { letter: 'O', relation: 'starts', clue: 'El Burrito, ídolo jujeño dueño de una gambeta inolvidable.', answer: 'Ortega', aliases: ['Ariel Ortega', 'Burrito Ortega'] },
    { letter: 'P', relation: 'starts', clue: 'Capitán y mediocampista campeón de América en 2015 y 2018.', answer: 'Ponzio', aliases: ['Leonardo Ponzio'] },
    { letter: 'Q', relation: 'starts', clue: 'Colombiano autor de uno de los goles más recordados de la final de Madrid.', answer: 'Quintero', aliases: ['Juan Fernando Quintero', 'Juanfer Quintero'] },
    { letter: 'R', relation: 'starts', clue: 'Delantero y entrenador riojano apodado el Pelado, múltiple campeón con River.', answer: 'Ramón Díaz', aliases: ['Ramon Diaz', 'Pelado Diaz', 'Pelado Díaz'] },
    { letter: 'S', relation: 'starts', clue: 'Delantero chileno apodado el Matador, campeón de la Supercopa 1997.', answer: 'Salas', aliases: ['Marcelo Salas', 'Matador Salas'] },
    { letter: 'T', relation: 'starts', clue: 'Apodo del arquero Barovero, héroe del penal ante Boca en la Sudamericana 2014.', answer: 'Trapito', aliases: ['Marcelo Barovero', 'Barovero'] },
    { letter: 'U', relation: 'contains', clue: 'Arquero surgido en el club que integró el plantel campeón de América en 2018.', answer: 'Lux', aliases: ['German Lux', 'Germán Lux', 'Poroto Lux'] },
    { letter: 'V', relation: 'starts', clue: 'Lateral izquierdo campeón de la Libertadores 2015, famoso por su despliegue.', answer: 'Vangioni', aliases: ['Leonel Vangioni'] },
    { letter: 'W', relation: 'starts', clue: 'Delantero uruguayo, gran figura de River durante la década de 1950.', answer: 'Walter Gómez', aliases: ['Walter Gomez', 'Gomez', 'Gómez'] },
    { letter: 'X', relation: 'contains', clue: 'Delantero surgido en River que luego jugó en Barcelona y Milan.', answer: 'Maxi López', aliases: ['Maxi Lopez', 'Maximiliano Lopez', 'Maximiliano López'] },
    { letter: 'Y', relation: 'starts', clue: 'Mediocampista histórico de La Máquina, apodado Pacho.', answer: 'Yácono', aliases: ['Yacono', 'Norberto Yacono', 'Norberto Yácono'] },
    { letter: 'Z', relation: 'starts', clue: 'Mediocampista surgido en River, de nombre Bruno, campeón de la Libertadores 2018.', answer: 'Zuculini', aliases: ['Bruno Zuculini'] },
  ],
};
