import { RoscoCategory, RoscoQuestion } from './roscodle.models';

export type RoscoSeed = readonly [answer: string, clue: string, aliases?: readonly string[]];

const ALPHABET = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] as const;

export function createRosco(seeds: readonly RoscoSeed[]): RoscoQuestion[] {
  if (seeds.length !== ALPHABET.length) {
    throw new Error(`Un rosco debe tener ${ALPHABET.length} preguntas; se recibieron ${seeds.length}.`);
  }

  return seeds.map(([answer, clue, aliases], index) => {
    const letter = ALPHABET[index];
    const normalizedAnswer = answer.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    const normalizedLetter = letter.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    const includesLetter = letter === 'Ñ'
      ? answer.toLocaleLowerCase('es').includes('ñ')
      : normalizedAnswer.includes(normalizedLetter);
    if (!includesLetter) throw new Error(`La respuesta "${answer}" no contiene la letra ${letter}.`);
    return {
      letter,
      relation: letter !== 'Ñ' && normalizedAnswer.startsWith(normalizedLetter) ? 'starts' : 'contains',
      clue,
      answer,
      aliases: aliases ? [...aliases] : undefined,
    };
  });
}

export const EXTRA_ROSCO_QUESTIONS: Pick<Record<RoscoCategory, RoscoQuestion[]>,
  'independiente' | 'racing' | 'san-lorenzo' | 'talleres' | 'belgrano' |
  'premier-league' | 'la-liga' | 'serie-a' | 'bundesliga' | 'ligue-1'> = {
  independiente: createRosco([
    ['Avellaneda', 'Ciudad bonaerense en la que tiene su estadio Independiente.'],
    ['Bochini', 'El Bocha, máximo ídolo y jugador con más partidos del club.', ['Ricardo Bochini', 'Bocha']],
    ['Copa Libertadores', 'Competición que el Rojo ganó siete veces, récord continental.', ['Libertadores']],
    ['Diablos Rojos', 'Apodo del equipo popularizado por su delantera de 1926.', ['Diablo Rojo', 'Diablos']],
    ['Erico', 'Delantero paraguayo y máximo goleador histórico del fútbol argentino.', ['Arsenio Erico']],
    ['Falcioni', 'Arquero del club en los ochenta y entrenador en distintas etapas.', ['Julio Cesar Falcioni', 'Julio César Falcioni']],
    ['Gabbarini', 'Arquero surgido de las inferiores que debutó en Primera en 2009.', ['Adrian Gabbarini', 'Adrián Gabbarini']],
    ['Holan', 'Entrenador campeón de la Sudamericana 2017.', ['Ariel Holan']],
    ['Independiente', 'Nombre por el que se conoce al Club Atlético fundado en 1905.'],
    ['Jorge Burruchaga', 'Autor del gol argentino en la final del Mundial 1986 y figura roja.', ['Burruchaga']],
    ['Kun Agüero', 'Apodo del delantero surgido en el Rojo que debutó con 15 años.', ['Aguero', 'Agüero', 'Sergio Aguero', 'Sergio Agüero']],
    ['Libertadores', 'La copa que consolidó el apodo de Rey de Copas.'],
    ['Marangoni', 'Volante elegante, campeón de América y del mundo en 1984.', ['Claudio Marangoni']],
    ['Nacional 1977', 'Torneo ganado ante Talleres con ocho jugadores en la recordada final de Córdoba.', ['Nacional del 77', 'Nacional 77']],
    ['Años setenta', 'Década en la que Independiente ganó cuatro Libertadores consecutivas.', ['Los años setenta', 'Setenta']],
    ['Omar Pastoriza', 'El Pato: campeón como jugador y como entrenador del Rojo.', ['Pastoriza', 'Pato Pastoriza']],
    ['Pavoni', 'Capitán uruguayo que levantó cinco Copas Libertadores.', ['Ricardo Pavoni', 'Chivo Pavoni']],
    ['Ricardo Enrique Bochini', 'Nombre completo del Bocha, el máximo ídolo de Independiente.', ['Bochini', 'Ricardo Bochini']],
    ['Rey de Copas', 'Apodo nacido de la extraordinaria cosecha internacional del club.'],
    ['Santoro', 'Pepe, arquero con más partidos en la historia de Independiente.', ['Miguel Angel Santoro', 'Miguel Ángel Santoro', 'Pepe Santoro']],
    ['Tagliafico', 'Lateral y capitán del campeón de la Sudamericana 2017.', ['Nicolas Tagliafico', 'Nicolás Tagliafico']],
    ['Uruguay', 'País de origen de Ricardo Pavoni, capitán histórico del Rojo.'],
    ['Vicente de la Mata', 'Delantero rosarino, integrante del célebre trío con Erico y Sastre.', ['De la Mata']],
    ['Walter Erviti', 'Experimentado volante que vistió la camiseta de Independiente en 2017.', ['Erviti']],
    ['Maxi Meza', 'Volante clave del título sudamericano de 2017.', ['Maximiliano Meza', 'Meza']],
    ['Yoyó Miani', 'Apodo de Atilio Miani, delantero campeón con el Rojo en 1948.', ['Yoyo Miani', 'Atilio Miani', 'Miani']],
    ['Zielinski', 'Entrenador que dirigió al primer equipo durante 2023.', ['Ricardo Zielinski']],
  ]),

  racing: createRosco([
    ['Academia', 'El apodo más reconocido de Racing Club.', ['La Academia']],
    ['Basile', 'El Coco, campeón como jugador y técnico de la Supercopa 1988.', ['Alfio Basile', 'Coco Basile']],
    ['Cárdenas', 'El Chango, autor del gol al Celtic que valió la Intercontinental de 1967.', ['Cardenas', 'Juan Carlos Cardenas', 'Juan Carlos Cárdenas', 'Chango Cardenas']],
    ['Diego Milito', 'El Príncipe, capitán y goleador del campeón de 2014.', ['Milito', 'Principe Milito', 'Príncipe Milito']],
    ['Estadio Presidente Perón', 'Nombre oficial del Cilindro de Avellaneda.', ['Presidente Peron', 'Presidente Perón']],
    ['Fillol', 'El Pato, arquero campeón del mundo que se formó en Racing.', ['Ubaldo Fillol', 'Pato Fillol']],
    ['Gustavo Costas', 'Defensor, capitán y entrenador profundamente identificado con el club.', ['Costas']],
    ['Hauche', 'El Demonio, delantero de varias etapas en la Academia.', ['Gabriel Hauche', 'Demonio Hauche']],
    ['Intercontinental', 'Copa que Racing ganó en 1967 para ser el primer club argentino campeón del mundo.'],
    ['Juan José Pizzuti', 'Entrenador del Equipo de José, campeón de América y del mundo.', ['Juan Jose Pizzuti', 'Pizzuti']],
    ['Kappa', 'Marca italiana que vistió a Racing durante parte de la década de 1990.'],
    ['Lisandro López', 'Licha, goleador y capitán del campeón de la Superliga 2018/19.', ['Lisandro Lopez', 'Licha Lopez', 'Licha López']],
    ['Mostaza Merlo', 'Entrenador campeón en 2001, asociado al inolvidable paso a paso.', ['Merlo', 'Reinaldo Merlo', 'Mostaza']],
    ['Natalio Perinetti', 'Histórico wing derecho que jugó más de 400 partidos para Racing.', ['Perinetti']],
    ['El Sueño del Pibe', 'Nombre de la pensión y proyecto juvenil de la Academia.', ['Sueño del Pibe']],
    ['Olé', 'Diario que popularizó la expresión paso a paso durante el Apertura 2001.'],
    ['Pizzuti', 'Apellido del técnico que condujo al histórico equipo de 1966 y 1967.', ['Juan Jose Pizzuti', 'Juan José Pizzuti']],
    ['Equipo de José', 'Apodo del Racing invicto y campeón dirigido por Pizzuti.', ['El Equipo de Jose', 'Equipo de Jose']],
    ['Racing Club', 'Nombre del club de Avellaneda conocido como la Academia.', ['Racing']],
    ['Saja', 'El Chino, arquero y capitán del equipo campeón en 2014.', ['Sebastian Saja', 'Sebastián Saja', 'Chino Saja']],
    ['Tita Mattiussi', 'Nombre del predio donde se forman los juveniles de Racing.', ['Predio Tita Mattiussi', 'Tita']],
    ['Supercopa 1988', 'Título internacional obtenido ante Cruzeiro bajo la conducción de Basile.', ['Supercopa', 'Supercopa Sudamericana']],
    ['Vietto', 'Delantero surgido en Racing que regresó al club tras una larga carrera internacional.', ['Luciano Vietto']],
    ['Washington Corbatta', 'El Loco, extraordinario puntero derecho bicampeón con Racing.', ['Corbatta', 'Oreste Corbatta', 'Loco Corbatta']],
    ['Maxi Moralez', 'Frasquito, enganche surgido del club y campeón en 2005 con la Sub-20.', ['Maximiliano Moralez', 'Moralez', 'Frasquito']],
    ['Yacob', 'La Flaca, volante central surgido de las inferiores y capitán.', ['Claudio Yacob']],
    ['Zaracho', 'Mediocampista de la cantera, campeón de la Superliga 2018/19.', ['Matias Zaracho', 'Matías Zaracho']],
  ]),

  'san-lorenzo': createRosco([
    ['Almagro', 'Barrio mencionado en el nombre completo original del club.'],
    ['Boedo', 'Barrio porteño inseparable de la identidad de San Lorenzo.'],
    ['Ciclón', 'Apodo nacido por la fuerza arrolladora del equipo de 1932.', ['Ciclon', 'El Ciclon', 'El Ciclón']],
    ["D'Alessandro", 'Andrés, talentoso volante que cerró su carrera argentina en el Ciclón.', ['Dalessandro', 'Andres D Alessandro', 'Andrés D Alessandro']],
    ['Estadio Pedro Bidegain', 'Nombre oficial del Nuevo Gasómetro.', ['Pedro Bidegain']],
    ['Facundo Quignón', 'Volante surgido en River que fue campeón con San Lorenzo en 2015.', ['Facundo Quignon', 'Quignon', 'Quignón']],
    ['Gasómetro', 'Nombre popular del histórico estadio de Avenida La Plata.', ['El Gasometro', 'El Gasómetro']],
    ['Héctor Scotta', 'El Gringo, formidable goleador azulgrana de los años setenta.', ['Hector Scotta', 'Scotta']],
    ['Insúa', 'El Gallego, campeón como jugador en 1995 y entrenador en 2002.', ['Ruben Insua', 'Rubén Insúa', 'Gallego Insua']],
    ['José Sanfilippo', 'El Nene, máximo goleador histórico del club.', ['Jose Sanfilippo', 'Sanfilippo', 'Nene Sanfilippo']],
    ['Kalinski', 'Volante del plantel que conquistó la Libertadores 2014.', ['Enzo Kalinski']],
    ['Leandro Romagnoli', 'El Pipi, jugador con más títulos en la historia azulgrana.', ['Romagnoli', 'Pipi Romagnoli']],
    ['Matadores', 'Apodo del brillante equipo campeón invicto en 1968.', ['Los Matadores']],
    ['Nuevo Gasómetro', 'Nombre popular del estadio inaugurado en 1993.', ['El Nuevo Gasometro', 'Nuevo Gasometro']],
    ['Peña azulgrana', 'Agrupación de hinchas del Ciclón fuera de Boedo.'],
    ['Ortigoza', 'Autor del penal que definió la final de la Libertadores 2014.', ['Nestor Ortigoza', 'Néstor Ortigoza', 'Orti']],
    ['Papa Francisco', 'Célebre socio e hincha de San Lorenzo nacido como Jorge Bergoglio.', ['Francisco', 'Jorge Bergoglio', 'Bergoglio']],
    ['Quignón', 'Apellido del mediocampista campeón de la Supercopa Argentina 2015.', ['Facundo Quignon', 'Facundo Quignón']],
    ['Romagnoli', 'Apellido del Pipi, emblema y campeón de la Libertadores.', ['Leandro Romagnoli', 'Pipi']],
    ['Sanfilippo', 'Apellido del Nene, goleador cuatro veces consecutivas del campeonato argentino.', ['Jose Sanfilippo', 'José Sanfilippo']],
    ['Torrico', 'El Cóndor, arquero clave en la Libertadores 2014.', ['Sebastian Torrico', 'Sebastián Torrico', 'Condor Torrico', 'Cóndor Torrico']],
    ['Rubén Darío Insúa', 'Nombre completo del Gallego, campeón como jugador y entrenador.', ['Ruben Dario Insua', 'Insua', 'Insúa']],
    ['Veira', 'El Bambino, entrenador del campeón de 1995.', ['Hector Veira', 'Héctor Veira', 'Bambino Veira']],
    ['Walter Perazzo', 'Delantero formado en el club que integró el plantel argentino en Italia 1990.', ['Perazzo']],
    ['Alexis Cuello', 'Delantero argentino que llegó al club desde Almagro.', ['Cuello']],
    ['Yeison Gordillo', 'Volante colombiano que vistió la camiseta azulgrana.', ['Gordillo']],
    ['Zabaleta', 'Lateral formado en San Lorenzo, campeón olímpico y figura del Manchester City.', ['Pablo Zabaleta']],
  ]),

  talleres: createRosco([
    ['Albiazul', 'Gentilicio futbolero que combina los dos colores tradicionales de Talleres.'],
    ['Barrio Jardín', 'Barrio cordobés donde se encuentra la sede y la cancha del club.'],
    ['Copa Conmebol', 'Competición internacional que Talleres ganó en 1999.', ['Conmebol']],
    ['Daniel Willington', 'El famoso Daniel de talento exquisito, uno de los grandes ídolos de la T.', ['Willington']],
    ['Estadio Mario Alberto Kempes', 'Escenario provincial donde Talleres disputa sus partidos de mayor convocatoria.', ['Mario Alberto Kempes', 'Estadio Kempes', 'Kempes']],
    ['Frank Kudelka', 'Entrenador de los ascensos consecutivos que devolvieron al club a Primera.', ['Kudelka']],
    ['Gandolfi', 'Defensor, capitán y luego entrenador del Matador.', ['Javier Gandolfi', 'Cobija Gandolfi']],
    ['Héctor Baley', 'Arquero campeón del mundo en 1978 que brilló en Talleres.', ['Hector Baley', 'Baley']],
    ['Instituto', 'Club cordobés ante el que Talleres disputa uno de los clásicos de la ciudad.'],
    ['Javier Pastore', 'El Flaco, enganche surgido de las inferiores albiazules.', ['Pastore', 'Flaco Pastore']],
    ['Kempes', 'Apellido del campeón mundial que da nombre al principal estadio de Córdoba.', ['Mario Kempes', 'Mario Alberto Kempes']],
    ['Ludueña', 'El Hacha, mediocampista con récord de presencias en Talleres.', ['Miguel Ludueña', 'Miguel Luduena', 'Hacha Ludueña']],
    ['Miguel Ángel Oviedo', 'Volante campeón mundial en 1978 y figura del Talleres de los setenta.', ['Miguel Angel Oviedo', 'Oviedo']],
    ['Nahuel Bustos', 'Delantero surgido en el club y goleador de la temporada 2019/20.', ['Bustos']],
    ['Peña albiazul', 'Agrupación de hinchas de Talleres fuera de Barrio Jardín.'],
    ['Oliva', 'Cristian, volante uruguayo que integró el equipo albiazul.', ['Cristian Oliva']],
    ['Pablo Guiñazú', 'El Cholo, capitán del ascenso y referente moderno de la T.', ['Pablo Guinazu', 'Guiñazu', 'Guiñazú', 'Cholo Guinazu']],
    ['Quintana', 'Carlos, defensor que logró con Talleres el ascenso a Primera en 2016.', ['Carlos Quintana']],
    ['Rodrigo Garro', 'Enganche cordobés que se destacó en Talleres antes de pasar a Corinthians.', ['Garro']],
    ['Saporiti', 'Entrenador del histórico subcampeón Nacional de 1977.', ['Roberto Saporiti']],
    ['Talleres', 'Nombre del club de Barrio Jardín conocido como la T o el Matador.'],
    ['Luis Galván', 'Defensor de Talleres titular en la Argentina campeona del mundo de 1978.', ['Luis Galvan', 'Galvan', 'Galván']],
    ['Valoyes', 'Extremo colombiano destacado en el club antes de ser transferido a México.', ['Diego Valoyes']],
    ['Willington', 'Apellido del Daniel cordobés, símbolo del fútbol elegante de Talleres.', ['Daniel Willington']],
    ['Alex Vigo', 'Lateral derecho que llegó al club a préstamo desde River.', ['Vigo']],
    ['Yamil Asad', 'Volante ofensivo argentino que jugó en Talleres en 2021.', ['Asad']],
    ['Zárate', 'Mauro, delantero de extensa trayectoria que tuvo un paso por Talleres.', ['Zarate', 'Mauro Zarate', 'Mauro Zárate']],
  ]),

  belgrano: createRosco([
    ['Alberdi', 'Barrio cordobés que es el corazón de Belgrano.'],
    ['Belgrano', 'Nombre del club celeste fundado en 1905.'],
    ['Celeste', 'Color y apodo principal del equipo de Alberdi.', ['El Celeste']],
    ['Destéfano', 'Arturo, uno de los máximos goleadores históricos del Pirata.', ['Destefano', 'Arturo Destefano', 'Arturo Destéfano']],
    ['Estadio Julio César Villagra', 'Nombre oficial del Gigante de Alberdi.', ['Julio Cesar Villagra', 'Julio César Villagra']],
    ['Farré', 'Guillermo, autor del gol del ascenso ante River y luego entrenador del club.', ['Farre', 'Guillermo Farre', 'Guillermo Farré']],
    ['Gigante de Alberdi', 'Nombre popular del estadio de Belgrano.', ['El Gigante de Alberdi', 'Gigante']],
    ['Héctor Rivoira', 'El Chulo, entrenador que condujo a Belgrano al ascenso de 2006.', ['Hector Rivoira', 'Rivoira', 'Chulo Rivoira']],
    ['Instituto', 'Rival cordobés con el que Belgrano disputa uno de los clásicos de la ciudad.'],
    ['Juan Carlos Olave', 'Arquero, capitán y gran referente del ascenso de 2011.', ['Olave', 'Juanca Olave']],
    ['Kempes', 'Estadio provincial en el que el Pirata juega encuentros de gran convocatoria.', ['Mario Alberto Kempes', 'Estadio Kempes']],
    ['Luifa Artime', 'Apodo y apellido del máximo goleador histórico de Belgrano.', ['Luis Fabian Artime', 'Luis Fabián Artime', 'Artime', 'Luifa']],
    ['Matías Suárez', 'Delantero surgido en el Pirata que brilló también en Anderlecht.', ['Matias Suarez', 'Suarez', 'Suárez']],
    ['Nahuel Luján', 'Atacante surgido en las inferiores conocido como el Gato.', ['Nahuel Lujan', 'Lujan', 'Luján']],
    ['Peña pirata', 'Agrupación de hinchas celestes lejos de Alberdi.'],
    ['Olave', 'Apellido del arquero que atajó el recordado penal a Pavone en 2011.', ['Juan Carlos Olave']],
    ['Pirata', 'El apodo más popular de Belgrano.', ['El Pirata']],
    ['Quiroga', 'Juan Quiroga, lateral izquierdo de varias temporadas en el club.', ['Juan Quiroga']],
    ['River Plate', 'Rival al que Belgrano venció en la Promoción de 2011.', ['River']],
    ['Suárez', 'Apellido de Matías, delantero de gran calidad surgido en el club.', ['Suarez', 'Matias Suarez', 'Matías Suárez']],
    ['Turco Artime', 'Apodo del goleador Luis Fabián Artime.', ['Artime', 'Luifa Artime', 'Luis Artime']],
    ['Uvita Fernández', 'Delantero argentino que se incorporó al Pirata en 2024.', ['Uvita Fernandez', 'Nicolas Fernandez', 'Nicolás Fernández']],
    ['Vegetti', 'Delantero y capitán, goleador del ascenso de 2022.', ['Pablo Vegetti']],
    ['Wilfredo Olivera', 'Defensor central cordobés con varias etapas en Belgrano.', ['Olivera']],
    ['Maxi Rigoni', 'Volante nacido futbolísticamente en el Pirata antes de pasar a Independiente.', ['Maximiliano Rigoni', 'Rigoni']],
    ['Yacob', 'Claudio, volante central que se sumó a Belgrano en 2022.', ['Claudio Yacob']],
    ['Zelarayán', 'El Chino, enganche surgido en Belgrano e ídolo moderno del club.', ['Zelarayan', 'Lucas Zelarayan', 'Lucas Zelarayán', 'Chino Zelarayan']],
  ]),

  'premier-league': createRosco([
    ['Arsenal', 'Club londinense apodado los Gunners.'],
    ['Beckham', 'Volante de extraordinaria pegada surgido en Manchester United.', ['David Beckham']],
    ['Chelsea', 'Club azul de Londres que juega en Stamford Bridge.'],
    ['De Bruyne', 'Volante belga que se convirtió en leyenda del Manchester City.', ['Kevin De Bruyne']],
    ['Emirates Stadium', 'Estadio del Arsenal desde 2006.', ['Emirates']],
    ['Ferguson', 'Sir Alex, entrenador más laureado de Manchester United.', ['Alex Ferguson', 'Sir Alex Ferguson']],
    ['Guardiola', 'Técnico catalán que condujo la era más ganadora del City.', ['Pep Guardiola', 'Pep']],
    ['Haaland', 'Goleador noruego que batió el récord de goles en una temporada Premier.', ['Erling Haaland']],
    ['Invincibles', 'Apodo del Arsenal campeón invicto de la Premier 2003/04.', ['The Invincibles', 'Los Invencibles']],
    ['John Terry', 'Capitán histórico del Chelsea y referente de su defensa.', ['Terry']],
    ['Klopp', 'Entrenador alemán que devolvió la liga inglesa al Liverpool.', ['Jurgen Klopp', 'Jürgen Klopp']],
    ['Liverpool', 'Club de Anfield identificado con You’ll Never Walk Alone.'],
    ['Manchester', 'Ciudad compartida por United y City.'],
    ['Neville', 'Gary, lateral y capitán de la generación dorada del United.', ['Gary Neville']],
    ['España', 'País de origen de Pep Guardiola, entrenador del Manchester City.'],
    ['Old Trafford', 'Estadio de Manchester United conocido como el Teatro de los Sueños.'],
    ['Premier League', 'Nombre de la máxima categoría inglesa desde 1992.', ['Premier']],
    ['Quinton Fortune', 'Volante sudafricano que jugó siete temporadas en Manchester United.', ['Fortune']],
    ['Rooney', 'Máximo goleador histórico de Manchester United.', ['Wayne Rooney']],
    ['Stamford Bridge', 'Estadio del Chelsea desde su fundación.'],
    ['Thierry Henry', 'Delantero francés y máximo goleador histórico del Arsenal.', ['Henry']],
    ['United', 'Palabra que completa el nombre del gigante rojo de Manchester.', ['Manchester United']],
    ['Van Dijk', 'Defensor neerlandés, pilar del Liverpool campeón con Klopp.', ['Virgil Van Dijk']],
    ['Wenger', 'Entrenador francés que dirigió al Arsenal durante 22 años.', ['Arsene Wenger', 'Arsène Wenger']],
    ['Xabi Alonso', 'Mediocampista español campeón de Europa con Liverpool en 2005.', ['Xabi']],
    ['Yaya Touré', 'Volante marfileño fundamental en el crecimiento del Manchester City.', ['Yaya Toure', 'Touré', 'Toure']],
    ['Zabaleta', 'Lateral argentino y referente del primer gran Manchester City de la era Premier.', ['Pablo Zabaleta']],
  ]),

  'la-liga': createRosco([
    ['Atlético de Madrid', 'Club rojiblanco de la capital española dirigido durante años por Simeone.', ['Atletico Madrid', 'Atlético Madrid', 'Atletico de Madrid']],
    ['Barcelona', 'Club catalán asociado al lema Més que un club.', ['FC Barcelona', 'Barca', 'Barça']],
    ['Camp Nou', 'Estadio histórico del Barcelona.'],
    ['Di Stéfano', 'La Saeta Rubia, leyenda que transformó la historia del Real Madrid.', ['Di Stefano', 'Alfredo Di Stefano', 'Alfredo Di Stéfano']],
    ['Estadio de Mestalla', 'Casa del Valencia desde 1923.', ['Mestalla']],
    ['Fernando Torres', 'El Niño, delantero surgido y convertido en símbolo del Atlético.', ['Torres', 'Niño Torres']],
    ['Griezmann', 'Atacante francés, uno de los máximos goleadores del Atlético.', ['Antoine Griezmann']],
    ['Hugo Sánchez', 'Goleador mexicano que brilló en Atlético y Real Madrid.', ['Hugo Sanchez']],
    ['Iniesta', 'Autor del gol del Mundial 2010 y leyenda del Barcelona.', ['Andres Iniesta', 'Andrés Iniesta']],
    ['Joaquín', 'Extremo andaluz de larguísima trayectoria que también jugó en Valencia.', ['Joaquin', 'Joaquín Sanchez', 'Joaquín Sánchez']],
    ['Koke', 'Capitán y futbolista con más partidos en la historia del Atlético.', ['Jorge Resurreccion', 'Jorge Resurrección']],
    ['LaLiga', 'Nombre comercial de la primera división española.', ['Liga', 'La Liga']],
    ['Mestalla', 'Estadio del Valencia conocido por sus tribunas empinadas.'],
    ['Nervión', 'Barrio sevillano en el que se levanta el Ramón Sánchez-Pizjuán.', ['Nervion']],
    ['España', 'País cuya primera división protagoniza este rosco.'],
    ['Ocampos', 'Extremo argentino que se convirtió en referente del Sevilla.', ['Lucas Ocampos']],
    ['Pichichi', 'Nombre del trofeo que recibe el máximo goleador de LaLiga.'],
    ['Quique Sánchez Flores', 'Entrenador español con pasos por Atlético, Valencia y Sevilla.', ['Quique Sanchez Flores', 'Quique Flores']],
    ['Real Madrid', 'Club blanco que juega en el Santiago Bernabéu.', ['Madrid']],
    ['Sevilla', 'Club andaluz récord de títulos de Europa League.', ['Sevilla FC']],
    ['Turia', 'Río y antiguo cauce que atraviesa la ciudad de Valencia.'],
    ['Luis Suárez', 'Delantero uruguayo campeón de liga con Barcelona y Atlético.', ['Luis Suarez', 'Suarez', 'Suárez']],
    ['Valencia', 'Club de Mestalla cuyo escudo luce un murciélago.', ['Valencia CF']],
    ['Wanda Metropolitano', 'Nombre que tuvo el actual estadio Metropolitano del Atlético entre 2017 y 2022.', ['Wanda']],
    ['Xavi', 'Mediocampista legendario y luego entrenador del Barcelona.', ['Xavi Hernandez', 'Xavi Hernández']],
    ['Youssef En-Nesyri', 'Delantero marroquí que superó el centenar de partidos con Sevilla.', ['En Nesyri', 'En-Nesyri']],
    ['Zidane', 'Francés que ganó Champions con el Real Madrid como jugador y entrenador.', ['Zinedine Zidane']],
  ]),

  'serie-a': createRosco([
    ['Allianz Stadium', 'Estadio de la Juventus en Turín.'],
    ['Bianconeri', 'Apodo italiano de la Juventus por sus colores blanco y negro.', ['La Vecchia Signora']],
    ['Calcio', 'Palabra italiana utilizada para nombrar al fútbol.'],
    ['Derby della Madonnina', 'Clásico que enfrenta a Milan e Inter.', ['Derbi della Madonnina', 'Madonnina']],
    ['Estadio Diego Armando Maradona', 'Casa del Napoli, antes conocida como San Paolo.', ['Diego Armando Maradona', 'Estadio Maradona']],
    ['Facchetti', 'Legendario lateral y capitán de la Grande Inter.', ['Giacinto Facchetti']],
    ['Giuseppe Meazza', 'Nombre oficial del estadio compartido por Inter y Milan.', ['Meazza', 'San Siro']],
    ['Higuaín', 'Goleador argentino que batió el récord de tantos de una temporada con Napoli.', ['Higuain', 'Gonzalo Higuain', 'Gonzalo Higuaín']],
    ['Inter', 'Club nerazzurro de Milán, rival del Milan.', ['Internazionale']],
    ['Juventus', 'Club de Turín conocido como la Vecchia Signora.', ['Juve']],
    ['Kaká', 'Brasileño Balón de Oro 2007 con el Milan.', ['Kaka', 'Ricardo Kaka']],
    ['Lautaro Martínez', 'Delantero argentino y capitán del Inter.', ['Lautaro', 'Lautaro Martinez']],
    ['Milan', 'Club rossonero siete veces campeón de Europa.', ['AC Milan']],
    ['Napoli', 'Club del sur italiano que idolatra a Diego Maradona.', ['Napoles', 'Nápoles']],
    ['Vieja Señora', 'Traducción al español del apodo Vecchia Signora de la Juventus.', ['La Vieja Señora', 'Vecchia Signora', 'La Vecchia Signora']],
    ['Olímpico de Roma', 'Estadio que la Roma comparte con Lazio.', ['Olimpico', 'Olímpico']],
    ['Paolo Maldini', 'Defensor que desarrolló toda su carrera profesional en Milan.', ['Maldini']],
    ['Quagliarella', 'Delantero italiano que vistió la camiseta de Juventus y fue goleador de Serie A.', ['Fabio Quagliarella']],
    ['Roma', 'Club giallorosso de la capital italiana.', ['AS Roma']],
    ['San Siro', 'Nombre popular del estadio de Milan e Inter.', ['Giuseppe Meazza', 'Meazza']],
    ['Totti', 'Il Capitano, máximo goleador y jugador con más presencias de la Roma.', ['Francesco Totti']],
    ['Curva Sud', 'Sector de San Siro asociado tradicionalmente a los tifosi del Milan.'],
    ['Vlahović', 'Delantero serbio de la Juventus.', ['Vlahovic', 'Dusan Vlahovic', 'Dušan Vlahović']],
    ['Walter Mazzarri', 'Entrenador italiano de varias etapas al frente del Napoli.', ['Mazzarri']],
    ['Alexis Sánchez', 'Delantero chileno con pasos por Inter y Udinese.', ['Alexis Sanchez', 'Alexis']],
    ['Yildiz', 'Kenan, atacante turco formado en Bayern y consolidado en Juventus.', ['Kenan Yildiz']],
    ['Zanetti', 'El Pupi, capitán argentino del Inter campeón de todo en 2010.', ['Javier Zanetti', 'Pupi Zanetti']],
  ]),

  bundesliga: createRosco([
    ['Allianz Arena', 'Estadio del Bayern Múnich.'],
    ['Bayern Múnich', 'Club más ganador de la Bundesliga.', ['Bayern Munich', 'Bayern']],
    ['Commerzbank-Arena', 'Nombre que tuvo el estadio del Eintracht Frankfurt entre 2005 y 2020.', ['Commerzbank Arena']],
    ['Dortmund', 'Ciudad y nombre corto del club dueño del Muro Amarillo.', ['Borussia Dortmund', 'BVB']],
    ['Eintracht Frankfurt', 'Club de las Águilas que juega a orillas del Meno.', ['Eintracht', 'Frankfurt']],
    ['Frankfurt', 'Ciudad del Eintracht y gran centro financiero alemán.'],
    ['Götze', 'Autor del gol de la final del Mundial 2014, formado en Dortmund.', ['Gotze', 'Mario Gotze', 'Mario Götze']],
    ['Heynckes', 'Jupp, entrenador del triplete del Bayern en 2013.', ['Jupp Heynckes']],
    ['Invictos', 'Condición con la que Leverkusen terminó la Bundesliga 2023/24.', ['Invicto']],
    ['Jürgen Klopp', 'Entrenador de los dos títulos consecutivos del Dortmund en 2011 y 2012.', ['Jurgen Klopp', 'Klopp']],
    ['Kimmich', 'Mediocampista alemán convertido en referente del Bayern.', ['Joshua Kimmich']],
    ['Leverkusen', 'Club de la aspirina que ganó invicto su primera Bundesliga.', ['Bayer Leverkusen', 'Bayer 04']],
    ['Müller', 'Thomas, campeón mundial y leyenda de una sola camiseta: Bayern.', ['Muller', 'Thomas Muller', 'Thomas Müller']],
    ['Neuer', 'Arquero que redefinió el puesto y capitaneó al Bayern.', ['Manuel Neuer']],
    ['España', 'País de Xabi Alonso, técnico del Leverkusen campeón invicto.'],
    ['Oliver Kahn', 'El Titán, arquero legendario del Bayern.', ['Kahn']],
    ['Philipp Lahm', 'Capitán del Bayern y de la Alemania campeona mundial en 2014.', ['Lahm']],
    ['Qatar Airways', 'Aerolínea que fue patrocinador de manga del Bayern hasta 2023.', ['Qatar']],
    ['RB Leipzig', 'Club sajón fundado en 2009 que se instaló entre los protagonistas.', ['Leipzig']],
    ['Signal Iduna Park', 'Nombre comercial del estadio del Borussia Dortmund.', ['Westfalenstadion']],
    ['Thomas Müller', 'Atacante bávaro especialista en encontrar espacios.', ['Thomas Muller', 'Muller', 'Müller']],
    ['Bundesliga', 'Máxima categoría del fútbol alemán.'],
    ['Völler', 'Rudi, histórico delantero y dirigente del Bayer Leverkusen.', ['Voller', 'Rudi Voller', 'Rudi Völler']],
    ['Westfalenstadion', 'Nombre tradicional de la cancha del Dortmund.', ['Signal Iduna Park']],
    ['Xabi Alonso', 'Entrenador que condujo al Leverkusen a su primera Bundesliga.', ['Xabi']],
    ['Yussuf Poulsen', 'Delantero danés que acompañó al Leipzig desde las divisiones inferiores.', ['Poulsen']],
    ['Zé Roberto', 'Brasileño de extensa y exitosa etapa en Bayern y Leverkusen.', ['Ze Roberto']],
  ]),

  'ligue-1': createRosco([
    ['Aulas', 'Jean-Michel, presidente del Lyon durante su etapa más ganadora.', ['Jean Michel Aulas', 'Jean-Michel Aulas']],
    ['Benzema', 'Delantero surgido en la cantera del Olympique de Lyon.', ['Karim Benzema']],
    ['Coupe de France', 'Nombre de la principal copa nacional francesa.', ['Copa de Francia']],
    ['Dembélé', 'Moussa, delantero francés con una destacada etapa en Lyon.', ['Dembele', 'Moussa Dembele', 'Moussa Dembélé']],
    ['Eden Hazard', 'Extremo belga que fue campeón y figura con Lille.', ['Hazard']],
    ['Falcao', 'El Tigre colombiano, goleador y campeón con Monaco.', ['Radamel Falcao', 'Tigre Falcao']],
    ['Ginola', 'Talentoso extremo francés que brilló en PSG.', ['David Ginola']],
    ['Hatem Ben Arfa', 'Mediapunta francés surgido en Lyon y con paso por PSG.', ['Ben Arfa']],
    ['Ibrahimović', 'Goleador sueco que dominó la liga con el PSG.', ['Ibrahimovic', 'Zlatan', 'Zlatan Ibrahimovic']],
    ['Juninho', 'Brasileño especialista en tiros libres y leyenda del Lyon.', ['Juninho Pernambucano']],
    ['Kylian Mbappé', 'Delantero campeón con Monaco y máximo goleador histórico del PSG.', ['Kylian Mbappe', 'Mbappe', 'Mbappé']],
    ['Lille', 'Club del norte francés conocido como los Dogues.', ['LOSC']],
    ['Marseille', 'Ciudad del único club francés campeón de Champions.', ['Marsella', 'Olympique de Marseille', 'Olympique de Marsella']],
    ['Neymar', 'Brasileño que llegó al PSG en 2017 por una cifra récord.', ['Neymar Jr']],
    ['España', 'País de Luis Enrique, entrenador que llegó al PSG en 2023.'],
    ['Olympique Lyonnais', 'Nombre completo del club de Lyon.', ['Olympique de Lyon', 'Lyon', 'OL']],
    ['Paris Saint-Germain', 'Club de la capital francesa conocido por sus siglas PSG.', ['PSG', 'Paris Saint Germain']],
    ['Qatar Sports Investments', 'Grupo propietario del PSG desde 2011.', ['QSI', 'Qatar']],
    ['Rudi Garcia', 'Entrenador francés que dirigió a Lille, Marseille y Lyon.', ['Garcia', 'Rudi García']],
    ['Stade Louis II', 'Estadio del Monaco situado en el distrito de Fontvieille.', ['Luis II', 'Louis II']],
    ['Trophée des Champions', 'Supercopa que enfrenta a los campeones franceses.', ['Trophee des Champions', 'Supercopa de Francia']],
    ['Luis Enrique', 'Técnico español del Paris Saint-Germain.', ['Luis Enrique Martinez', 'Luis Enrique Martínez']],
    ['Vélodrome', 'Estadio del Olympique de Marseille.', ['Velodrome', 'Stade Velodrome', 'Stade Vélodrome']],
    ['Wissam Ben Yedder', 'Delantero francés que fue capitán y goleador del Monaco.', ['Ben Yedder']],
    ['Auxerre', 'Club borgoñón campeón de Francia en 1996.', ['AJ Auxerre']],
    ['Yoro', 'Leny, defensor formado en Lille antes de partir a Inglaterra.', ['Leny Yoro']],
    ['Zlatan', 'Nombre del goleador sueco Ibrahimović, gran figura del PSG.', ['Ibrahimovic', 'Ibrahimović', 'Zlatan Ibrahimovic']],
  ]),
};
