export interface FootballerEntry {
  answer: string;
  player: string;
  country: string;
}

export const FOOTBALLERS: readonly FootballerEntry[] = [
  { answer: 'MESSI', player: 'Lionel Messi', country: 'Argentina' },
  { answer: 'RONALDO', player: 'Cristiano Ronaldo', country: 'Portugal' },
  { answer: 'MBAPPE', player: 'Kylian Mbappé', country: 'Francia' },
  { answer: 'NEYMAR', player: 'Neymar Jr.', country: 'Brasil' },
  { answer: 'SUAREZ', player: 'Luis Suárez', country: 'Uruguay' },
  { answer: 'MODRIC', player: 'Luka Modrić', country: 'Croacia' },
  { answer: 'KROOS', player: 'Toni Kroos', country: 'Alemania' },
  { answer: 'INIESTA', player: 'Andrés Iniesta', country: 'España' },
  { answer: 'XAVI', player: 'Xavi Hernández', country: 'España' },
  { answer: 'ZIDANE', player: 'Zinédine Zidane', country: 'Francia' },
  { answer: 'HENRY', player: 'Thierry Henry', country: 'Francia' },
  { answer: 'PIRLO', player: 'Andrea Pirlo', country: 'Italia' },
  { answer: 'MALDINI', player: 'Paolo Maldini', country: 'Italia' },
  { answer: 'BUFFON', player: 'Gianluigi Buffon', country: 'Italia' },
  { answer: 'TOTTI', player: 'Francesco Totti', country: 'Italia' },
  { answer: 'KAKA', player: 'Kaká', country: 'Brasil' },
  { answer: 'RONALDINHO', player: 'Ronaldinho', country: 'Brasil' },
  { answer: 'RIVALDO', player: 'Rivaldo', country: 'Brasil' },
  { answer: 'ROMARIO', player: 'Romário', country: 'Brasil' },
  { answer: 'PELE', player: 'Pelé', country: 'Brasil' },
  { answer: 'MARADONA', player: 'Diego Maradona', country: 'Argentina' },
  { answer: 'BATISTUTA', player: 'Gabriel Batistuta', country: 'Argentina' },
  { answer: 'RIQUELME', player: 'Juan Román Riquelme', country: 'Argentina' },
  { answer: 'AGUERO', player: 'Sergio Agüero', country: 'Argentina' },
  { answer: 'DI MARIA', player: 'Ángel Di María', country: 'Argentina' },
  { answer: 'LAUTARO', player: 'Lautaro Martínez', country: 'Argentina' },
  { answer: 'ALVAREZ', player: 'Julián Álvarez', country: 'Argentina' },
  { answer: 'GRIEZMANN', player: 'Antoine Griezmann', country: 'Francia' },
  { answer: 'BENZEMA', player: 'Karim Benzema', country: 'Francia' },
  { answer: 'GIROUD', player: 'Olivier Giroud', country: 'Francia' },
  { answer: 'PLATINI', player: 'Michel Platini', country: 'Francia' },
  { answer: 'HAALAND', player: 'Erling Haaland', country: 'Noruega' },
  { answer: 'ODEGAARD', player: 'Martin Ødegaard', country: 'Noruega' },
  { answer: 'SALAH', player: 'Mohamed Salah', country: 'Egipto' },
  { answer: 'MANE', player: 'Sadio Mané', country: 'Senegal' },
  { answer: 'DROGBA', player: 'Didier Drogba', country: 'Costa de Marfil' },
  { answer: 'ETO O', player: "Samuel Eto'o", country: 'Camerún' },
  { answer: 'MAHREZ', player: 'Riyad Mahrez', country: 'Argelia' },
  { answer: 'OSIMHEN', player: 'Victor Osimhen', country: 'Nigeria' },
  { answer: 'KANE', player: 'Harry Kane', country: 'Inglaterra' },
  { answer: 'BECKHAM', player: 'David Beckham', country: 'Inglaterra' },
  { answer: 'ROONEY', player: 'Wayne Rooney', country: 'Inglaterra' },
  { answer: 'GERRARD', player: 'Steven Gerrard', country: 'Inglaterra' },
  { answer: 'LAMPARD', player: 'Frank Lampard', country: 'Inglaterra' },
  { answer: 'SCHOLES', player: 'Paul Scholes', country: 'Inglaterra' },
  { answer: 'SHEARER', player: 'Alan Shearer', country: 'Inglaterra' },
  { answer: 'BELLINGHAM', player: 'Jude Bellingham', country: 'Inglaterra' },
  { answer: 'SAKA', player: 'Bukayo Saka', country: 'Inglaterra' },
  { answer: 'FODEN', player: 'Phil Foden', country: 'Inglaterra' },
  { answer: 'DE BRUYNE', player: 'Kevin De Bruyne', country: 'Bélgica' },
  { answer: 'HAZARD', player: 'Eden Hazard', country: 'Bélgica' },
  { answer: 'COURTOIS', player: 'Thibaut Courtois', country: 'Bélgica' },
  { answer: 'LEWANDOWSKI', player: 'Robert Lewandowski', country: 'Polonia' },
  { answer: 'IBRAHIMOVIC', player: 'Zlatan Ibrahimović', country: 'Suecia' },
  { answer: 'SON', player: 'Son Heung-min', country: 'Corea del Sur' },
  { answer: 'PARK', player: 'Park Ji-sung', country: 'Corea del Sur' },
  { answer: 'NAKATA', player: 'Hidetoshi Nakata', country: 'Japón' },
  { answer: 'VIDIC', player: 'Nemanja Vidić', country: 'Serbia' },
  { answer: 'SAVICEVIC', player: 'Dejan Savićević', country: 'Montenegro' },
  { answer: 'SUKER', player: 'Davor Šuker', country: 'Croacia' },
  { answer: 'RAKITIC', player: 'Ivan Rakitić', country: 'Croacia' },
  { answer: 'SEEDORF', player: 'Clarence Seedorf', country: 'Países Bajos' },
  { answer: 'CRUYFF', player: 'Johan Cruyff', country: 'Países Bajos' },
  { answer: 'ROBBEN', player: 'Arjen Robben', country: 'Países Bajos' },
  { answer: 'BERGKAMP', player: 'Dennis Bergkamp', country: 'Países Bajos' },
  { answer: 'VAN DIJK', player: 'Virgil van Dijk', country: 'Países Bajos' },
  { answer: 'GULLIT', player: 'Ruud Gullit', country: 'Países Bajos' },
  { answer: 'VAN BASTEN', player: 'Marco van Basten', country: 'Países Bajos' },
  { answer: 'MUSIALA', player: 'Jamal Musiala', country: 'Alemania' },
  { answer: 'MULLER', player: 'Thomas Müller', country: 'Alemania' },
  { answer: 'KLOSE', player: 'Miroslav Klose', country: 'Alemania' },
  { answer: 'BECKENBAUER', player: 'Franz Beckenbauer', country: 'Alemania' },
  { answer: 'NEUER', player: 'Manuel Neuer', country: 'Alemania' },
  { answer: 'MATTHAUS', player: 'Lothar Matthäus', country: 'Alemania' },
  { answer: 'FIGO', player: 'Luís Figo', country: 'Portugal' },
  { answer: 'EUSEBIO', player: 'Eusébio', country: 'Portugal' },
  { answer: 'CANCELO', player: 'João Cancelo', country: 'Portugal' },
  { answer: 'RAMOS', player: 'Sergio Ramos', country: 'España' },
  { answer: 'CASILLAS', player: 'Iker Casillas', country: 'España' },
  { answer: 'BUSQUETS', player: 'Sergio Busquets', country: 'España' },
  { answer: 'RODRI', player: 'Rodri', country: 'España' },
  { answer: 'VILLA', player: 'David Villa', country: 'España' },
  { answer: 'TORRES', player: 'Fernando Torres', country: 'España' },
  { answer: 'PUYOL', player: 'Carles Puyol', country: 'España' },
  { answer: 'DEL PIERO', player: 'Alessandro Del Piero', country: 'Italia' },
  { answer: 'BARESI', player: 'Franco Baresi', country: 'Italia' },
  { answer: 'CANNAVARO', player: 'Fabio Cannavaro', country: 'Italia' },
  { answer: 'BAGGIO', player: 'Roberto Baggio', country: 'Italia' },
  { answer: 'YASHIN', player: 'Lev Yashin', country: 'Unión Soviética' },
  { answer: 'SHEVCHENKO', player: 'Andriy Shevchenko', country: 'Ucrania' },
  { answer: 'PUSKAS', player: 'Ferenc Puskás', country: 'Hungría' },
  { answer: 'WEAH', player: 'George Weah', country: 'Liberia' }
].map(player => ({ ...player, answer: player.answer.replace(/[^A-Z]/g, '') }));
