export interface FootballerEntry {
  answer: string;
  player: string;
  country: string;
}

export const FOOTBALLERS: readonly FootballerEntry[] = [
  { answer: 'MESSI', player: 'Lionel Messi', country: 'Argentina' },
  { answer: 'RONALDO', player: 'Cristiano Ronaldo', country: 'Portugal' },
  { answer: 'MBAPPE', player: 'Kylian Mbappé', country: 'Francia' },
  { answer: 'NEYMAR', player: 'Neymar Jr.', country: 'Brasil' },
  { answer: 'SUAREZ', player: 'Luis Suárez', country: 'Uruguay' },
  { answer: 'MODRIC', player: 'Luka Modrić', country: 'Croacia' },
  { answer: 'KROOS', player: 'Toni Kroos', country: 'Alemania' },
  { answer: 'INIESTA', player: 'Andrés Iniesta', country: 'España' },
  { answer: 'XAVI', player: 'Xavi Hernández', country: 'España' },
  { answer: 'ZIDANE', player: 'Zinédine Zidane', country: 'Francia' },
  { answer: 'HENRY', player: 'Thierry Henry', country: 'Francia' },
  { answer: 'PIRLO', player: 'Andrea Pirlo', country: 'Italia' },
  { answer: 'MALDINI', player: 'Paolo Maldini', country: 'Italia' },
  { answer: 'BUFFON', player: 'Gianluigi Buffon', country: 'Italia' },
  { answer: 'TOTTI', player: 'Francesco Totti', country: 'Italia' },
  { answer: 'KAKA', player: 'Kaká', country: 'Brasil' },
  { answer: 'RONALDINHO', player: 'Ronaldinho', country: 'Brasil' },
  { answer: 'RIVALDO', player: 'Rivaldo', country: 'Brasil' },
  { answer: 'ROMARIO', player: 'Romário', country: 'Brasil' },
  { answer: 'PELE', player: 'Pelé', country: 'Brasil' },
  { answer: 'MARADONA', player: 'Diego Maradona', country: 'Argentina' },
  { answer: 'BATISTUTA', player: 'Gabriel Batistuta', country: 'Argentina' },
  { answer: 'RIQUELME', player: 'Juan Román Riquelme', country: 'Argentina' },
  { answer: 'AGUERO', player: 'Sergio Agüero', country: 'Argentina' },
  { answer: 'DI MARIA', player: 'Ángel Di María', country: 'Argentina' },
  { answer: 'LAUTARO', player: 'Lautaro Martínez', country: 'Argentina' },
  { answer: 'ALVAREZ', player: 'Julián Álvarez', country: 'Argentina' },
  { answer: 'GRIEZMANN', player: 'Antoine Griezmann', country: 'Francia' },
  { answer: 'BENZEMA', player: 'Karim Benzema', country: 'Francia' },
  { answer: 'GIROUD', player: 'Olivier Giroud', country: 'Francia' },
  { answer: 'PLATINI', player: 'Michel Platini', country: 'Francia' },
  { answer: 'HAALAND', player: 'Erling Haaland', country: 'Noruega' },
  { answer: 'ODEGAARD', player: 'Martin Ødegaard', country: 'Noruega' },
  { answer: 'SALAH', player: 'Mohamed Salah', country: 'Egipto' },
  { answer: 'MANE', player: 'Sadio Mané', country: 'Senegal' },
  { answer: 'DROGBA', player: 'Didier Drogba', country: 'Costa de Marfil' },
  { answer: 'ETO O', player: "Samuel Eto'o", country: 'Camerún' },
  { answer: 'MAHREZ', player: 'Riyad Mahrez', country: 'Argelia' },
  { answer: 'OSIMHEN', player: 'Victor Osimhen', country: 'Nigeria' },
  { answer: 'KANE', player: 'Harry Kane', country: 'Inglaterra' },
  { answer: 'BECKHAM', player: 'David Beckham', country: 'Inglaterra' },
  { answer: 'ROONEY', player: 'Wayne Rooney', country: 'Inglaterra' },
  { answer: 'GERRARD', player: 'Steven Gerrard', country: 'Inglaterra' },
  { answer: 'LAMPARD', player: 'Frank Lampard', country: 'Inglaterra' },
  { answer: 'SCHOLES', player: 'Paul Scholes', country: 'Inglaterra' },
  { answer: 'SHEARER', player: 'Alan Shearer', country: 'Inglaterra' },
  { answer: 'BELLINGHAM', player: 'Jude Bellingham', country: 'Inglaterra' },
  { answer: 'SAKA', player: 'Bukayo Saka', country: 'Inglaterra' },
  { answer: 'FODEN', player: 'Phil Foden', country: 'Inglaterra' },
  { answer: 'DE BRUYNE', player: 'Kevin De Bruyne', country: 'Bélgica' },
  { answer: 'HAZARD', player: 'Eden Hazard', country: 'Bélgica' },
  { answer: 'COURTOIS', player: 'Thibaut Courtois', country: 'Bélgica' },
  { answer: 'LEWANDOWSKI', player: 'Robert Lewandowski', country: 'Polonia' },
  { answer: 'IBRAHIMOVIC', player: 'Zlatan Ibrahimović', country: 'Suecia' },
  { answer: 'SON', player: 'Son Heung-min', country: 'Corea del Sur' },
  { answer: 'PARK', player: 'Park Ji-sung', country: 'Corea del Sur' },
  { answer: 'NAKATA', player: 'Hidetoshi Nakata', country: 'Japón' },
  { answer: 'VIDIC', player: 'Nemanja Vidić', country: 'Serbia' },
  { answer: 'SAVICEVIC', player: 'Dejan Savićević', country: 'Montenegro' },
  { answer: 'SUKER', player: 'Davor Šuker', country: 'Croacia' },
  { answer: 'RAKITIC', player: 'Ivan Rakitić', country: 'Croacia' },
  { answer: 'SEEDORF', player: 'Clarence Seedorf', country: 'Países Bajos' },
  { answer: 'CRUYFF', player: 'Johan Cruyff', country: 'Países Bajos' },
  { answer: 'ROBBEN', player: 'Arjen Robben', country: 'Países Bajos' },
  { answer: 'BERGKAMP', player: 'Dennis Bergkamp', country: 'Países Bajos' },
  { answer: 'VAN DIJK', player: 'Virgil van Dijk', country: 'Países Bajos' },
  { answer: 'GULLIT', player: 'Ruud Gullit', country: 'Países Bajos' },
  { answer: 'VAN BASTEN', player: 'Marco van Basten', country: 'Países Bajos' },
  { answer: 'MUSIALA', player: 'Jamal Musiala', country: 'Alemania' },
  { answer: 'MULLER', player: 'Thomas Müller', country: 'Alemania' },
  { answer: 'KLOSE', player: 'Miroslav Klose', country: 'Alemania' },
  { answer: 'BECKENBAUER', player: 'Franz Beckenbauer', country: 'Alemania' },
  { answer: 'NEUER', player: 'Manuel Neuer', country: 'Alemania' },
  { answer: 'MATTHAUS', player: 'Lothar Matthäus', country: 'Alemania' },
  { answer: 'FIGO', player: 'Luís Figo', country: 'Portugal' },
  { answer: 'EUSEBIO', player: 'Eusébio', country: 'Portugal' },
  { answer: 'CANCELO', player: 'João Cancelo', country: 'Portugal' },
  { answer: 'RAMOS', player: 'Sergio Ramos', country: 'España' },
  { answer: 'CASILLAS', player: 'Iker Casillas', country: 'España' },
  { answer: 'BUSQUETS', player: 'Sergio Busquets', country: 'España' },
  { answer: 'RODRI', player: 'Rodri', country: 'España' },
  { answer: 'VILLA', player: 'David Villa', country: 'España' },
  { answer: 'TORRES', player: 'Fernando Torres', country: 'España' },
  { answer: 'PUYOL', player: 'Carles Puyol', country: 'España' },
  { answer: 'DEL PIERO', player: 'Alessandro Del Piero', country: 'Italia' },
  { answer: 'BARESI', player: 'Franco Baresi', country: 'Italia' },
  { answer: 'CANNAVARO', player: 'Fabio Cannavaro', country: 'Italia' },
  { answer: 'BAGGIO', player: 'Roberto Baggio', country: 'Italia' },
  { answer: 'YASHIN', player: 'Lev Yashin', country: 'Unión Soviética' },
  { answer: 'SHEVCHENKO', player: 'Andriy Shevchenko', country: 'Ucrania' },
  { answer: 'PUSKAS', player: 'Ferenc Puskás', country: 'Hungría' },
  { answer: 'WEAH', player: 'George Weah', country: 'Liberia' },
  { answer: 'TEVEZ', player: 'Carlos Tévez', country: 'Argentina' },
  { answer: 'AIMAR', player: 'Pablo Aimar', country: 'Argentina' },
  { answer: 'GATTI', player: 'Hugo Gatti', country: 'Argentina' },
  { answer: 'LOPEZ', player: 'Claudio López', country: 'Argentina' },
  { answer: 'VERON', player: 'Juan Sebastián Verón', country: 'Argentina' },
  { answer: 'ALVES', player: 'Dani Alves', country: 'Brasil' },
  { answer: 'LUCIO', player: 'Lúcio', country: 'Brasil' },
  { answer: 'OSCAR', player: 'Oscar', country: 'Brasil' },
  { answer: 'JESUS', player: 'Gabriel Jesus', country: 'Brasil' },
  { answer: 'MARTA', player: 'Marta', country: 'Brasil' },
  { answer: 'GODIN', player: 'Diego Godín', country: 'Uruguay' },
  { answer: 'NUNEZ', player: 'Darwin Núñez', country: 'Uruguay' },
  { answer: 'POGBA', player: 'Paul Pogba', country: 'Francia' },
  { answer: 'KANTE', player: "N'Golo Kanté", country: 'Francia' },
  { answer: 'COMAN', player: 'Kingsley Coman', country: 'Francia' },
  { answer: 'LEMAR', player: 'Thomas Lemar', country: 'Francia' },
  { answer: 'PAYET', player: 'Dimitri Payet', country: 'Francia' },
  { answer: 'BLANC', player: 'Laurent Blanc', country: 'Francia' },
  { answer: 'PEDRI', player: 'Pedri', country: 'España' },
  { answer: 'PIQUE', player: 'Gerard Piqué', country: 'España' },
  { answer: 'SILVA', player: 'David Silva', country: 'España' },
  { answer: 'REINA', player: 'Pepe Reina', country: 'España' },
  { answer: 'NAVAS', player: 'Jesús Navas', country: 'España' },
  { answer: 'NESTA', player: 'Alessandro Nesta', country: 'Italia' },
  { answer: 'ROSSI', player: 'Paolo Rossi', country: 'Italia' },
  { answer: 'VIERI', player: 'Christian Vieri', country: 'Italia' },
  { answer: 'TERRY', player: 'John Terry', country: 'Inglaterra' },
  { answer: 'MOUNT', player: 'Mason Mount', country: 'Inglaterra' },
  { answer: 'VARDY', player: 'Jamie Vardy', country: 'Inglaterra' },
  { answer: 'BOWEN', player: 'Jarrod Bowen', country: 'Inglaterra' },
  { answer: 'BANKS', player: 'Gordon Banks', country: 'Inglaterra' },
  { answer: 'MOORE', player: 'Bobby Moore', country: 'Inglaterra' },
  { answer: 'GIGGS', player: 'Ryan Giggs', country: 'Gales' },
  { answer: 'KEANE', player: 'Roy Keane', country: 'Irlanda' },
  { answer: 'GOTZE', player: 'Mario Götze', country: 'Alemania' },
  { answer: 'DEPAY', player: 'Memphis Depay', country: 'Países Bajos' },
  { answer: 'KOVAC', player: 'Niko Kovač', country: 'Croacia' },
  { answer: 'SIMIC', player: 'Dario Šimić', country: 'Croacia' },
  { answer: 'TADIC', player: 'Dušan Tadić', country: 'Serbia' },
  { answer: 'JOVIC', player: 'Luka Jović', country: 'Serbia' },
  { answer: 'DZEKO', player: 'Edin Džeko', country: 'Bosnia y Herzegovina' },
  { answer: 'KJAER', player: 'Simon Kjær', country: 'Dinamarca' },
  { answer: 'MILIK', player: 'Arkadiusz Milik', country: 'Polonia' },
  { answer: 'BAROS', player: 'Milan Baroš', country: 'República Checa' },
  { answer: 'LUNIN', player: 'Andriy Lunin', country: 'Ucrania' },
  { answer: 'TOURE', player: 'Yaya Touré', country: 'Costa de Marfil' },
  { answer: 'KEITA', player: 'Seydou Keita', country: 'Malí' },
  { answer: 'MIKEL', player: 'John Obi Mikel', country: 'Nigeria' },
  { answer: 'MOSES', player: 'Victor Moses', country: 'Nigeria' },
  { answer: 'IWOBI', player: 'Alex Iwobi', country: 'Nigeria' },
  { answer: 'MBOMA', player: "Patrick M'Boma", country: 'Camerún' },
  { answer: 'ABEDI', player: 'Abedi Pelé', country: 'Ghana' },
  { answer: 'MENDY', player: 'Édouard Mendy', country: 'Senegal' },
  { answer: 'DIOUF', player: 'El Hadji Diouf', country: 'Senegal' },
  { answer: 'BRAVO', player: 'Claudio Bravo', country: 'Chile' },
  { answer: 'VIDAL', player: 'Arturo Vidal', country: 'Chile' },
  { answer: 'SUAZO', player: 'Humberto Suazo', country: 'Chile' },
  { answer: 'SALAS', player: 'Marcelo Salas', country: 'Chile' },
  { answer: 'OCHOA', player: 'Guillermo Ochoa', country: 'México' },
  { answer: 'JAMES', player: 'James Rodríguez', country: 'Colombia' },
  { answer: 'HONDA', player: 'Keisuke Honda', country: 'Japón' },
  { answer: 'CUEVA', player: 'Christian Cueva', country: 'Perú' },
  { answer: 'GOMEZ', player: 'Gustavo Gómez', country: 'Paraguay' },
  { answer: 'ALABA', player: 'David Alaba', country: 'Austria' },
  { answer: 'XHAKA', player: 'Granit Xhaka', country: 'Suiza' },
  { answer: 'DAVID', player: 'Jonathan David', country: 'Canadá' },
  { answer: 'COSTA', player: 'Rui Costa', country: 'Portugal' },
  { answer: 'PRINZ', player: 'Birgit Prinz', country: 'Alemania' }
].map(player => ({ ...player, answer: player.answer.replace(/[^A-Z]/g, '') }));
