import { ChronodleEvent } from './chronodle.models';

/**
 * Los eventos se agrupan por grandes periodos. El generador elige uno de cada
 * grupo para que cada partida tenga una progresión clara y evite fechas ambiguas.
 */
export const CHRONODLE_EVENT_ERAS: readonly (readonly ChronodleEvent[])[] = [
  [
    {
      id: 'magna-carta',
      title: 'Se firma la Carta Magna en Inglaterra',
      date: '1215-06-15',
      displayDate: '15 de junio de 1215',
      category: 'Política',
      region: 'Europa',
      summary: 'El documento limitó el poder de la corona inglesa y se convirtió en un antecedente del constitucionalismo.',
      sourceUrl: 'https://www.parliament.uk/magnacarta/',
    },
    {
      id: 'printing-press',
      title: 'Gutenberg desarrolla la imprenta de tipos móviles',
      date: '1440-01-01',
      displayDate: 'Hacia 1440',
      category: 'Cultura',
      region: 'Europa',
      summary: 'La impresión con tipos móviles permitió reproducir libros a una escala inédita en Europa.',
      sourceUrl: 'https://www.britannica.com/technology/printing-press',
    },
    {
      id: 'america-1492',
      title: 'La expedición de Colón llega a América',
      date: '1492-10-12',
      displayDate: '12 de octubre de 1492',
      category: 'Política',
      region: 'América',
      summary: 'La llegada de la expedición castellana inició una transformación profunda y violenta entre ambos lados del Atlántico.',
      sourceUrl: 'https://www.britannica.com/biography/Christopher-Columbus',
    },
    {
      id: 'copernicus',
      title: 'Se publica la teoría heliocéntrica de Copérnico',
      date: '1543-05-24',
      displayDate: '1543',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'La obra propuso que la Tierra y los demás planetas giran alrededor del Sol.',
      sourceUrl: 'https://science.nasa.gov/solar-system/',
    },
    {
      id: 'quijote',
      title: 'Se publica la primera parte de Don Quijote',
      date: '1605-01-16',
      displayDate: '16 de enero de 1605',
      category: 'Cultura',
      region: 'Europa',
      summary: 'La novela de Miguel de Cervantes se convirtió en una de las obras fundamentales de la literatura en español.',
      sourceUrl: 'https://www.cervantes.es/bibliotecas_documentacion_espanol/biografias/beirut_miguel_cervantes.htm',
    },
    {
      id: 'principia-newton',
      title: 'Newton publica los Principia Mathematica',
      date: '1687-07-05',
      displayDate: '5 de julio de 1687',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'La obra formuló las leyes del movimiento y la gravitación universal.',
      sourceUrl: 'https://www.britannica.com/topic/Principia',
    },
  ],
  [
    {
      id: 'us-independence',
      title: 'Estados Unidos declara su independencia',
      date: '1776-07-04',
      displayDate: '4 de julio de 1776',
      category: 'Política',
      region: 'América del Norte',
      summary: 'Las trece colonias proclamaron su separación de Gran Bretaña mediante la Declaración de Independencia.',
      sourceUrl: 'https://www.archives.gov/founding-docs/declaration',
    },
    {
      id: 'french-revolution',
      title: 'Comienza la Revolución francesa',
      date: '1789-07-14',
      displayDate: '14 de julio de 1789',
      category: 'Política',
      region: 'Europa',
      summary: 'La toma de la Bastilla simbolizó el inicio de una revolución que transformó Francia y Europa.',
      sourceUrl: 'https://www.britannica.com/event/French-Revolution',
    },
    {
      id: 'may-revolution',
      title: 'Ocurre la Revolución de Mayo',
      date: '1810-05-25',
      displayDate: '25 de mayo de 1810',
      category: 'Política',
      region: 'Argentina',
      summary: 'La formación de la Primera Junta abrió el proceso que conduciría a la independencia argentina.',
      sourceUrl: 'https://www.argentina.gob.ar/pais/25-mayo-revolucion',
    },
    {
      id: 'argentina-independence',
      title: 'Argentina declara su independencia',
      date: '1816-07-09',
      displayDate: '9 de julio de 1816',
      category: 'Política',
      region: 'Argentina',
      summary: 'El Congreso de Tucumán declaró la independencia de las Provincias Unidas del dominio español.',
      sourceUrl: 'https://www.argentina.gob.ar/pais/9-julio-independencia',
    },
    {
      id: 'origin-species',
      title: 'Darwin publica El origen de las especies',
      date: '1859-11-24',
      displayDate: '24 de noviembre de 1859',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'Charles Darwin presentó su explicación de la evolución por selección natural.',
      sourceUrl: 'https://www.nhm.ac.uk/discover/charles-darwin-most-famous-biologist.html',
    },
    {
      id: 'first-telephone',
      title: 'Bell realiza una llamada telefónica exitosa',
      date: '1876-03-10',
      displayDate: '10 de marzo de 1876',
      category: 'Ciencia',
      region: 'América del Norte',
      summary: 'Alexander Graham Bell transmitió una frase mediante un dispositivo telefónico funcional.',
      sourceUrl: 'https://www.loc.gov/item/today-in-history/march-10/',
    },
  ],
  [
    {
      id: 'first-flight',
      title: 'Los hermanos Wright realizan el primer vuelo controlado',
      date: '1903-12-17',
      displayDate: '17 de diciembre de 1903',
      category: 'Ciencia',
      region: 'América del Norte',
      summary: 'El Flyer permaneció en el aire durante 12 segundos en Kitty Hawk, Carolina del Norte.',
      sourceUrl: 'https://www.nps.gov/wrbr/learn/historyculture/thefirstflight.htm',
    },
    {
      id: 'world-war-one',
      title: 'Comienza la Primera Guerra Mundial',
      date: '1914-07-28',
      displayDate: '28 de julio de 1914',
      category: 'Política',
      region: 'Europa',
      summary: 'La declaración de guerra de Austria-Hungría a Serbia activó una cadena de alianzas internacionales.',
      sourceUrl: 'https://www.britannica.com/event/World-War-I',
    },
    {
      id: 'penicillin',
      title: 'Fleming descubre la penicilina',
      date: '1928-09-28',
      displayDate: '28 de septiembre de 1928',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'Alexander Fleming observó que un moho impedía el crecimiento de bacterias en su laboratorio.',
      sourceUrl: 'https://www.nobelprize.org/prizes/medicine/1945/summary/',
    },
    {
      id: 'first-world-cup',
      title: 'Se disputa el primer Mundial de fútbol',
      date: '1930-07-13',
      displayDate: '13 de julio de 1930',
      category: 'Deportes',
      region: 'Uruguay',
      summary: 'Uruguay recibió y ganó la primera Copa Mundial organizada por la FIFA.',
      sourceUrl: 'https://www.fifa.com/tournaments/mens/worldcup/1930uruguay',
    },
    {
      id: 'united-nations',
      title: 'Entra en vigor la Carta de las Naciones Unidas',
      date: '1945-10-24',
      displayDate: '24 de octubre de 1945',
      category: 'Política',
      region: 'Mundo',
      summary: 'La entrada en vigor de la Carta marcó el nacimiento oficial de la Organización de las Naciones Unidas.',
      sourceUrl: 'https://www.un.org/en/about-us/history-of-the-un',
    },
    {
      id: 'women-vote-argentina',
      title: 'Argentina sanciona el voto femenino',
      date: '1947-09-23',
      displayDate: '23 de septiembre de 1947',
      category: 'Sociedad',
      region: 'Argentina',
      summary: 'La Ley 13.010 reconoció a las mujeres argentinas los mismos derechos políticos que a los varones.',
      sourceUrl: 'https://www.argentina.gob.ar/noticias/23-de-septiembre-de-1947-se-promulgo-la-ley-del-voto-femenino',
    },
  ],
  [
    {
      id: 'dna-structure',
      title: 'Se publica el modelo de la estructura del ADN',
      date: '1953-04-25',
      displayDate: '25 de abril de 1953',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'La publicación del modelo de doble hélice cambió la comprensión de la herencia biológica.',
      sourceUrl: 'https://www.nature.com/scitable/topicpage/discovery-of-dna-structure-and-function-watson-397/',
    },
    {
      id: 'sputnik',
      title: 'La Unión Soviética lanza el Sputnik 1',
      date: '1957-10-04',
      displayDate: '4 de octubre de 1957',
      category: 'Ciencia',
      region: 'Eurasia',
      summary: 'El Sputnik 1 fue el primer satélite artificial colocado en órbita terrestre.',
      sourceUrl: 'https://www.nasa.gov/history/sputnik/index.html',
    },
    {
      id: 'moon-landing',
      title: 'El ser humano llega a la Luna',
      date: '1969-07-20',
      displayDate: '20 de julio de 1969',
      category: 'Ciencia',
      region: 'Espacio',
      summary: 'Neil Armstrong y Buzz Aldrin descendieron sobre la superficie lunar durante la misión Apolo 11.',
      sourceUrl: 'https://www.nasa.gov/mission/apollo-11/',
    },
    {
      id: 'argentina-democracy',
      title: 'Argentina recupera la democracia',
      date: '1983-12-10',
      displayDate: '10 de diciembre de 1983',
      category: 'Política',
      region: 'Argentina',
      summary: 'Raúl Alfonsín asumió la presidencia tras siete años de dictadura cívico-militar.',
      sourceUrl: 'https://www.argentina.gob.ar/noticias/10-de-diciembre-dia-de-la-restauracion-de-la-democracia',
    },
    {
      id: 'chernobyl',
      title: 'Ocurre el accidente nuclear de Chernóbil',
      date: '1986-04-26',
      displayDate: '26 de abril de 1986',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'La explosión del reactor número cuatro produjo el accidente nuclear más grave de la historia.',
      sourceUrl: 'https://www.iaea.org/newscenter/focus/chernobyl',
    },
    {
      id: 'berlin-wall',
      title: 'Cae el Muro de Berlín',
      date: '1989-11-09',
      displayDate: '9 de noviembre de 1989',
      category: 'Política',
      region: 'Europa',
      summary: 'La apertura de los pasos fronterizos aceleró la reunificación alemana y simbolizó el final de la Guerra Fría.',
      sourceUrl: 'https://www.britannica.com/event/Berlin-Wall',
    },
  ],
  [
    {
      id: 'world-wide-web',
      title: 'Se publica el primer sitio web',
      date: '1991-08-06',
      displayDate: '6 de agosto de 1991',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'Tim Berners-Lee publicó en el CERN el primer sitio de la World Wide Web.',
      sourceUrl: 'https://home.cern/science/computing/birth-web',
    },
    {
      id: 'mandela-president',
      title: 'Nelson Mandela asume la presidencia de Sudáfrica',
      date: '1994-05-10',
      displayDate: '10 de mayo de 1994',
      category: 'Política',
      region: 'África',
      summary: 'Mandela se convirtió en el primer presidente negro del país tras las primeras elecciones democráticas multirraciales.',
      sourceUrl: 'https://www.nelsonmandela.org/content/page/biography',
    },
    {
      id: 'google-founded',
      title: 'Se funda Google',
      date: '1998-09-04',
      displayDate: '4 de septiembre de 1998',
      category: 'Ciencia',
      region: 'América del Norte',
      summary: 'Larry Page y Sergey Brin constituyeron la empresa que desarrolló uno de los buscadores más utilizados del mundo.',
      sourceUrl: 'https://about.google/our-story/',
    },
    {
      id: 'human-genome',
      title: 'Se completa el Proyecto Genoma Humano',
      date: '2003-04-14',
      displayDate: '14 de abril de 2003',
      category: 'Ciencia',
      region: 'Mundo',
      summary: 'El consorcio internacional anunció la finalización de la secuencia de referencia del genoma humano.',
      sourceUrl: 'https://www.genome.gov/human-genome-project',
    },
    {
      id: 'first-iphone',
      title: 'Apple presenta el primer iPhone',
      date: '2007-01-09',
      displayDate: '9 de enero de 2007',
      category: 'Ciencia',
      region: 'América del Norte',
      summary: 'El dispositivo combinó teléfono, navegación web y reproducción multimedia en una interfaz táctil.',
      sourceUrl: 'https://www.apple.com/newsroom/2007/01/09Apple-Reinvents-the-Phone-with-iPhone/',
    },
    {
      id: 'higgs-boson',
      title: 'El CERN anuncia el descubrimiento del bosón de Higgs',
      date: '2012-07-04',
      displayDate: '4 de julio de 2012',
      category: 'Ciencia',
      region: 'Europa',
      summary: 'Los experimentos ATLAS y CMS observaron una nueva partícula compatible con el bosón de Higgs.',
      sourceUrl: 'https://home.cern/science/physics/higgs-boson',
    },
    {
      id: 'black-hole-image',
      title: 'Se presenta la primera imagen de un agujero negro',
      date: '2019-04-10',
      displayDate: '10 de abril de 2019',
      category: 'Ciencia',
      region: 'Espacio',
      summary: 'El Event Horizon Telescope reveló la sombra del agujero negro de la galaxia M87.',
      sourceUrl: 'https://www.eso.org/public/news/eso1907/',
    },
    {
      id: 'james-webb-launch',
      title: 'Se lanza el telescopio espacial James Webb',
      date: '2021-12-25',
      displayDate: '25 de diciembre de 2021',
      category: 'Ciencia',
      region: 'Espacio',
      summary: 'El observatorio partió hacia el punto de Lagrange L2 para estudiar las primeras etapas del universo.',
      sourceUrl: 'https://science.nasa.gov/mission/webb/',
    },
  ],
] as const;
