import {
  FutbolMayorComparison,
  FutbolMayorCompetitor,
} from './futbol-mayor.models';

const UEFA_SCORERS =
  'https://www.uefa.com/uefachampionsleague/news/0257-0e910cf2494a-5185150de9d4-1000--champions-league-all-time-top-scorers-cristiano-/';
const UEFA_SOUTH_AMERICA =
  'https://www.uefa.com/news/0252-0d044f6082ee-2d26fd1c024f-1000--europe-s-top-south-american-stars/';
const UEFA_TITLES =
  'https://www.uefa.com/news/0275-1541637ad1db-88aeeefefefd-1000--all-time-honours-board/';
const FIFA_WINS =
  'https://www.fifa.com/en/tournaments/mens/worldcup/articles/teams-most-victories-wins';
const FIFA_TITLES =
  'https://www.fifa.com/pt/articles/espanha-iguala-franca-uruguai-ultrapassa-inglaterra-entre-maiores-campeoes-mundiais';
const PL_RECORDS = 'https://www.premierleague.com/en/stats/records';
const PL_GOALS = 'https://www.premierleague.com/en/news/4218966';
const PL_ASSISTS = 'https://www.premierleague.com/en/news/4260409';
const PL_TITLES = 'https://www.premierleague.com/en/news/4662306';
const PL_ROMERO =
  'https://www.premierleague.com/en/news/4576483/manchester-united-2-0-tottenham-hotspur-match-report-7-february-2026';

function competitor(
  id: string,
  name: string,
  shortName: string,
  initials: string,
  detail: string,
  value: number,
  accent: string,
): FutbolMayorCompetitor {
  return { id, name, shortName, initials, detail, value, accent };
}

/**
 * Catálogo editorial: cada duelo conserva alcance, fecha de corte y fuente.
 * No mezclar estos valores con amistosos, fases previas u otras competiciones.
 */
export const FUTBOL_MAYOR_COMPARISONS: readonly FutbolMayorComparison[] = [
  {
    id: 'ucl-ronaldo-messi',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '10 SEP 2026',
    unit: 'goles',
    left: competitor(
      'cristiano',
      'Cristiano Ronaldo',
      'Cristiano',
      'CR7',
      'Portugal · Delantero',
      140,
      '#f3d44f',
    ),
    right: competitor(
      'messi',
      'Lionel Messi',
      'Messi',
      'LM',
      'Argentina · Delantero',
      129,
      '#71c7ec',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SCORERS,
  },
  {
    id: 'ucl-lewa-benzema',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '10 SEP 2026',
    unit: 'goles',
    left: competitor(
      'lewandowski',
      'Robert Lewandowski',
      'Lewandowski',
      'RL9',
      'Polonia · Delantero',
      109,
      '#e85d5d',
    ),
    right: competitor(
      'benzema',
      'Karim Benzema',
      'Benzema',
      'KB9',
      'Francia · Delantero',
      90,
      '#d8d8d8',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SCORERS,
  },
  {
    id: 'ucl-mbappe-haaland',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '10 SEP 2026',
    unit: 'goles',
    left: competitor(
      'mbappe',
      'Kylian Mbappé',
      'Mbappé',
      'KM10',
      'Francia · Delantero',
      71,
      '#4067d6',
    ),
    right: competitor(
      'haaland',
      'Erling Haaland',
      'Haaland',
      'EH9',
      'Noruega · Delantero',
      59,
      '#70c6d9',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SCORERS,
  },
  {
    id: 'ucl-muller-kane',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '10 SEP 2026',
    unit: 'goles',
    left: competitor(
      'muller',
      'Thomas Müller',
      'Müller',
      'TM25',
      'Alemania · Mediapunta',
      57,
      '#d43838',
    ),
    right: competitor(
      'kane',
      'Harry Kane',
      'Kane',
      'HK9',
      'Inglaterra · Delantero',
      55,
      '#f1f1e6',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SCORERS,
  },
  {
    id: 'ucl-messi-neymar',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '30 MAY 2026',
    unit: 'goles',
    left: competitor(
      'messi',
      'Lionel Messi',
      'Messi',
      'LM',
      'Argentina · Delantero',
      129,
      '#71c7ec',
    ),
    right: competitor(
      'neymar',
      'Neymar Jr.',
      'Neymar',
      'NJ10',
      'Brasil · Delantero',
      43,
      '#e3e64c',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SOUTH_AMERICA,
  },
  {
    id: 'ucl-neymar-aguero',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '30 MAY 2026',
    unit: 'goles',
    left: competitor(
      'neymar',
      'Neymar Jr.',
      'Neymar',
      'NJ10',
      'Brasil · Delantero',
      43,
      '#e3e64c',
    ),
    right: competitor(
      'aguero',
      'Sergio Agüero',
      'Agüero',
      'SA10',
      'Argentina · Delantero',
      41,
      '#79b9df',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SOUTH_AMERICA,
  },
  {
    id: 'ucl-cavani-vinicius',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '30 MAY 2026',
    unit: 'goles',
    left: competitor(
      'cavani',
      'Edinson Cavani',
      'Cavani',
      'EC9',
      'Uruguay · Delantero',
      35,
      '#82c7ee',
    ),
    right: competitor(
      'vinicius',
      'Vinícius Júnior',
      'Vinícius',
      'VJ7',
      'Brasil · Delantero',
      34,
      '#e6df50',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SOUTH_AMERICA,
  },
  {
    id: 'ucl-kaka-suarez',
    category: 'Goles',
    question: '¿Quién hizo más goles?',
    metric: 'Goles en UEFA Champions League',
    scope: 'Fase de grupos/liguilla hasta la final; no incluye clasificación',
    cutoff: '30 MAY 2026',
    unit: 'goles',
    left: competitor(
      'kaka',
      'Kaká',
      'Kaká',
      'K22',
      'Brasil · Mediapunta',
      30,
      '#d65353',
    ),
    right: competitor(
      'suarez',
      'Luis Suárez',
      'Suárez',
      'LS9',
      'Uruguay · Delantero',
      27,
      '#73bee8',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_SOUTH_AMERICA,
  },
  {
    id: 'pl-kane-rooney',
    category: 'Goles',
    question: '¿Quién convirtió más?',
    metric: 'Goles históricos en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '5 ENE 2025',
    unit: 'goles',
    left: competitor(
      'kane',
      'Harry Kane',
      'Kane',
      'HK9',
      'Inglaterra · Delantero',
      213,
      '#e9e9e3',
    ),
    right: competitor(
      'rooney',
      'Wayne Rooney',
      'Rooney',
      'WR10',
      'Inglaterra · Delantero',
      208,
      '#dc4444',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_GOALS,
  },
  {
    id: 'pl-rooney-aguero',
    category: 'Goles',
    question: '¿Quién convirtió más?',
    metric: 'Goles históricos en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '5 ENE 2025',
    unit: 'goles',
    left: competitor(
      'rooney',
      'Wayne Rooney',
      'Rooney',
      'WR10',
      'Inglaterra · Delantero',
      208,
      '#dc4444',
    ),
    right: competitor(
      'aguero',
      'Sergio Agüero',
      'Agüero',
      'SA10',
      'Argentina · Delantero',
      184,
      '#79b9df',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_GOALS,
  },
  {
    id: 'pl-aguero-henry',
    category: 'Goles',
    question: '¿Quién convirtió más?',
    metric: 'Goles históricos en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '5 ENE 2025',
    unit: 'goles',
    left: competitor(
      'aguero',
      'Sergio Agüero',
      'Agüero',
      'SA10',
      'Argentina · Delantero',
      184,
      '#79b9df',
    ),
    right: competitor(
      'henry',
      'Thierry Henry',
      'Henry',
      'TH14',
      'Francia · Delantero',
      175,
      '#c63f45',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_GOALS,
  },
  {
    id: 'pl-season-haaland-salah',
    category: 'Goles',
    question: '¿Quién tuvo la temporada más goleadora?',
    metric: 'Mejor temporada goleadora en Premier League',
    scope: 'Haaland 2022/23 frente a Salah 2017/18',
    cutoff: 'TEMPORADAS COMPLETAS',
    unit: 'goles',
    left: competitor(
      'haaland',
      'Erling Haaland',
      'Haaland',
      'EH9',
      'Manchester City · 2022/23',
      36,
      '#70c6d9',
    ),
    right: competitor(
      'salah',
      'Mohamed Salah',
      'Salah',
      'MS11',
      'Liverpool · 2017/18',
      32,
      '#e44c51',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_ASSISTS,
  },
  {
    id: 'pl-assists-giggs-fabregas',
    category: 'Asistencias',
    question: '¿Quién dio más asistencias?',
    metric: 'Asistencias históricas en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '28 FEB 2025',
    unit: 'asistencias',
    left: competitor(
      'giggs',
      'Ryan Giggs',
      'Giggs',
      'RG11',
      'Gales · Mediocampista',
      162,
      '#d74040',
    ),
    right: competitor(
      'fabregas',
      'Cesc Fàbregas',
      'Fàbregas',
      'CF4',
      'España · Mediocampista',
      111,
      '#d7d7d0',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_ASSISTS,
  },
  {
    id: 'pl-assists-lampard-gerrard',
    category: 'Asistencias',
    question: '¿Quién dio más asistencias?',
    metric: 'Asistencias históricas en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '28 FEB 2025',
    unit: 'asistencias',
    left: competitor(
      'lampard',
      'Frank Lampard',
      'Lampard',
      'FL8',
      'Inglaterra · Mediocampista',
      102,
      '#2869a8',
    ),
    right: competitor(
      'gerrard',
      'Steven Gerrard',
      'Gerrard',
      'SG8',
      'Inglaterra · Mediocampista',
      92,
      '#d94040',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_ASSISTS,
  },
  {
    id: 'pl-assists-bergkamp-henry',
    category: 'Asistencias',
    question: '¿Quién dio más asistencias?',
    metric: 'Asistencias históricas en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '28 FEB 2025',
    unit: 'asistencias',
    left: competitor(
      'bergkamp',
      'Dennis Bergkamp',
      'Bergkamp',
      'DB10',
      'Países Bajos · Delantero',
      94,
      '#d34747',
    ),
    right: competitor(
      'henry',
      'Thierry Henry',
      'Henry',
      'TH14',
      'Francia · Delantero',
      74,
      '#c63f45',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_ASSISTS,
  },
  {
    id: 'pl-appearances-barry-giggs',
    category: 'Partidos',
    question: '¿Quién jugó más partidos?',
    metric: 'Apariciones históricas en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: 'CARRERAS COMPLETAS',
    unit: 'partidos',
    left: competitor(
      'barry',
      'Gareth Barry',
      'Barry',
      'GB18',
      'Inglaterra · Mediocampista',
      653,
      '#68409a',
    ),
    right: competitor(
      'giggs',
      'Ryan Giggs',
      'Giggs',
      'RG11',
      'Gales · Mediocampista',
      632,
      '#d74040',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_RECORDS,
  },
  {
    id: 'pl-red-vieira-romero',
    category: 'Disciplina',
    question: '¿Quién fue expulsado más veces?',
    metric: 'Tarjetas rojas en Premier League',
    scope: 'Todas las temporadas disputadas por cada jugador',
    cutoff: '7 FEB 2026',
    unit: 'rojas',
    left: competitor(
      'vieira',
      'Patrick Vieira',
      'Vieira',
      'PV4',
      'Francia · Mediocampista',
      8,
      '#cf4147',
    ),
    right: competitor(
      'romero',
      'Cristian Romero',
      'Cuti Romero',
      'CR17',
      'Argentina · Defensor',
      4,
      '#e6e6df',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_ROMERO,
  },
  {
    id: 'wc-wins-brazil-germany',
    category: 'Partidos',
    question: '¿Qué selección ganó más?',
    metric: 'Partidos ganados en Mundiales masculinos',
    scope: 'Desde 1930 hasta el Mundial 2026 inclusive',
    cutoff: '16 JUL 2026',
    unit: 'victorias',
    left: competitor(
      'brazil',
      'Brasil',
      'Brasil',
      'BRA',
      'Selección masculina',
      79,
      '#e2dd45',
    ),
    right: competitor(
      'germany',
      'Alemania',
      'Alemania',
      'GER',
      'Selección masculina',
      70,
      '#e8e8e0',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_WINS,
  },
  {
    id: 'wc-wins-argentina-france',
    category: 'Partidos',
    question: '¿Qué selección ganó más?',
    metric: 'Partidos ganados en Mundiales masculinos',
    scope: 'Desde 1930 hasta el Mundial 2026 inclusive',
    cutoff: '16 JUL 2026',
    unit: 'victorias',
    left: competitor(
      'argentina',
      'Argentina',
      'Argentina',
      'ARG',
      'Selección masculina',
      54,
      '#75c8ec',
    ),
    right: competitor(
      'france',
      'Francia',
      'Francia',
      'FRA',
      'Selección masculina',
      45,
      '#3659a8',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_WINS,
  },
  {
    id: 'wc-wins-england-netherlands',
    category: 'Partidos',
    question: '¿Qué selección ganó más?',
    metric: 'Partidos ganados en Mundiales masculinos',
    scope: 'Desde 1930 hasta el Mundial 2026 inclusive',
    cutoff: '16 JUL 2026',
    unit: 'victorias',
    left: competitor(
      'england',
      'Inglaterra',
      'Inglaterra',
      'ENG',
      'Selección masculina',
      38,
      '#eeeeea',
    ),
    right: competitor(
      'netherlands',
      'Países Bajos',
      'Países Bajos',
      'NED',
      'Selección masculina',
      32,
      '#ec762e',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_WINS,
  },
  {
    id: 'wc-wins-uruguay-belgium',
    category: 'Partidos',
    question: '¿Qué selección ganó más?',
    metric: 'Partidos ganados en Mundiales masculinos',
    scope: 'Desde 1930 hasta el Mundial 2026 inclusive',
    cutoff: '16 JUL 2026',
    unit: 'victorias',
    left: competitor(
      'uruguay',
      'Uruguay',
      'Uruguay',
      'URU',
      'Selección masculina',
      25,
      '#72bde7',
    ),
    right: competitor(
      'belgium',
      'Bélgica',
      'Bélgica',
      'BEL',
      'Selección masculina',
      24,
      '#dd3b3b',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_WINS,
  },
  {
    id: 'wc-wins-mexico-sweden',
    category: 'Partidos',
    question: '¿Qué selección ganó más?',
    metric: 'Partidos ganados en Mundiales masculinos',
    scope: 'Desde 1930 hasta el Mundial 2026 inclusive',
    cutoff: '16 JUL 2026',
    unit: 'victorias',
    left: competitor(
      'mexico',
      'México',
      'México',
      'MEX',
      'Selección masculina',
      21,
      '#3e9765',
    ),
    right: competitor(
      'sweden',
      'Suecia',
      'Suecia',
      'SWE',
      'Selección masculina',
      20,
      '#e5cf3f',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_WINS,
  },
  {
    id: 'wc-titles-brazil-germany',
    category: 'Títulos',
    question: '¿Qué selección fue campeona más veces?',
    metric: 'Títulos de Copa Mundial masculina',
    scope: 'Mundiales disputados entre 1930 y 2026',
    cutoff: '19 JUL 2026',
    unit: 'títulos',
    left: competitor(
      'brazil',
      'Brasil',
      'Brasil',
      'BRA',
      'Selección masculina',
      5,
      '#e2dd45',
    ),
    right: competitor(
      'germany',
      'Alemania',
      'Alemania',
      'GER',
      'Selección masculina',
      4,
      '#e8e8e0',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_TITLES,
  },
  {
    id: 'wc-titles-argentina-spain',
    category: 'Títulos',
    question: '¿Qué selección fue campeona más veces?',
    metric: 'Títulos de Copa Mundial masculina',
    scope: 'Mundiales disputados entre 1930 y 2026',
    cutoff: '19 JUL 2026',
    unit: 'títulos',
    left: competitor(
      'argentina',
      'Argentina',
      'Argentina',
      'ARG',
      'Selección masculina',
      3,
      '#75c8ec',
    ),
    right: competitor(
      'spain',
      'España',
      'España',
      'ESP',
      'Selección masculina',
      2,
      '#d74a3a',
    ),
    sourceLabel: 'FIFA',
    sourceUrl: FIFA_TITLES,
  },
  {
    id: 'ucl-titles-real-milan',
    category: 'Títulos',
    question: '¿Qué club levantó más veces la copa?',
    metric: 'Títulos de Copa de Europa / Champions League',
    scope: 'Ediciones disputadas entre 1955/56 y 2025/26',
    cutoff: '30 MAY 2026',
    unit: 'títulos',
    left: competitor(
      'real-madrid',
      'Real Madrid',
      'Real Madrid',
      'RMA',
      'España · Club',
      15,
      '#eeeeea',
    ),
    right: competitor(
      'milan',
      'AC Milan',
      'Milan',
      'ACM',
      'Italia · Club',
      7,
      '#d84242',
    ),
    sourceLabel: 'UEFA',
    sourceUrl: UEFA_TITLES,
  },
  {
    id: 'pl-titles-united-city',
    category: 'Títulos',
    question: '¿Qué club salió campeón más veces?',
    metric: 'Títulos de Premier League',
    scope: 'Desde la temporada 1992/93 hasta la 2025/26',
    cutoff: '19 MAY 2026',
    unit: 'títulos',
    left: competitor(
      'man-united',
      'Manchester United',
      'Man United',
      'MUN',
      'Inglaterra · Club',
      13,
      '#d83e45',
    ),
    right: competitor(
      'man-city',
      'Manchester City',
      'Man City',
      'MCI',
      'Inglaterra · Club',
      8,
      '#77c5e7',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_TITLES,
  },
  {
    id: 'pl-titles-chelsea-arsenal',
    category: 'Títulos',
    question: '¿Qué club salió campeón más veces?',
    metric: 'Títulos de Premier League',
    scope: 'Desde la temporada 1992/93 hasta la 2025/26',
    cutoff: '19 MAY 2026',
    unit: 'títulos',
    left: competitor(
      'chelsea',
      'Chelsea',
      'Chelsea',
      'CHE',
      'Inglaterra · Club',
      5,
      '#3165bc',
    ),
    right: competitor(
      'arsenal',
      'Arsenal',
      'Arsenal',
      'ARS',
      'Inglaterra · Club',
      4,
      '#dc4545',
    ),
    sourceLabel: 'Premier League',
    sourceUrl: PL_TITLES,
  },
];
